// Generated by CIRCT firtool-1.62.0
module Alu(	// src/main/scala/gba/cpu/Alu.scala:41:7
  input  [3:0]  io_opcode,	// src/main/scala/gba/cpu/Alu.scala:42:14
  input  [31:0] io_a,	// src/main/scala/gba/cpu/Alu.scala:42:14
                io_b,	// src/main/scala/gba/cpu/Alu.scala:42:14
  input         io_flagIn_c,	// src/main/scala/gba/cpu/Alu.scala:42:14
                io_flagIn_v,	// src/main/scala/gba/cpu/Alu.scala:42:14
                io_shifterCarry,	// src/main/scala/gba/cpu/Alu.scala:42:14
  output [31:0] io_out,	// src/main/scala/gba/cpu/Alu.scala:42:14
  output        io_flagOut_n,	// src/main/scala/gba/cpu/Alu.scala:42:14
                io_flagOut_z,	// src/main/scala/gba/cpu/Alu.scala:42:14
                io_flagOut_c,	// src/main/scala/gba/cpu/Alu.scala:42:14
                io_flagOut_v	// src/main/scala/gba/cpu/Alu.scala:42:14
);

  wire [31:0]       io_out_0;	// src/main/scala/gba/cpu/Alu.scala:67:22, :69:14
  wire              _GEN = io_opcode == 4'h4 | io_opcode == 4'hB;	// src/main/scala/gba/cpu/Alu.scala:67:22
  wire [32:0]       _GEN_0 = {1'h0, io_a};	// src/main/scala/gba/cpu/Alu.scala:67:22, :75:23
  wire [32:0]       _GEN_1 = {1'h0, io_b};	// src/main/scala/gba/cpu/Alu.scala:67:22, :75:23
  wire [32:0]       temp = _GEN_0 + _GEN_1;	// src/main/scala/gba/cpu/Alu.scala:75:23
  wire              _GEN_2 = io_opcode == 4'h5;	// src/main/scala/gba/cpu/Alu.scala:67:22
  wire [32:0]       temp_1 = _GEN_0 + _GEN_1 + {32'h0, io_flagIn_c};	// src/main/scala/gba/cpu/Alu.scala:62:26, :75:23, :81:31
  wire              _GEN_3 = io_opcode == 4'h2 | io_opcode == 4'hA;	// src/main/scala/gba/cpu/Alu.scala:67:22
  wire [32:0]       temp_2 = _GEN_0 - _GEN_1;	// src/main/scala/gba/cpu/Alu.scala:75:23, :87:23
  wire              _GEN_4 = io_opcode == 4'h6;	// src/main/scala/gba/cpu/Alu.scala:67:22
  wire [32:0]       temp_3 = _GEN_0 - _GEN_1 - {32'h0, ~io_flagIn_c};	// src/main/scala/gba/cpu/Alu.scala:62:26, :75:23, :93:{23,31,35}
  wire              _GEN_5 = io_opcode == 4'h3;	// src/main/scala/gba/cpu/Alu.scala:67:22
  wire [32:0]       temp_4 = _GEN_1 - _GEN_0;	// src/main/scala/gba/cpu/Alu.scala:75:23, :99:23
  wire              _GEN_6 = io_opcode == 4'h7;	// src/main/scala/gba/cpu/Alu.scala:67:22
  wire [32:0]       temp_5 = _GEN_1 - _GEN_0 - {32'h0, ~io_flagIn_c};	// src/main/scala/gba/cpu/Alu.scala:62:26, :75:23, :105:{23,31,35}
  wire              _GEN_7 = io_opcode == 4'hD | (&io_opcode);	// src/main/scala/gba/cpu/Alu.scala:63:16, :67:22
  wire [31:0]       _io_out_T_1 = io_a & io_b;	// src/main/scala/gba/cpu/Alu.scala:111:22
  wire [31:0]       _io_out_T_2 = io_a ^ io_b;	// src/main/scala/gba/cpu/Alu.scala:114:22
  wire [15:0][31:0] _GEN_8 =
    {{~io_b},
     {io_a & ~io_b},
     {io_b},
     {io_a | io_b},
     {temp[31:0]},
     {temp_2[31:0]},
     {_io_out_T_2},
     {_io_out_T_1},
     {temp_5[31:0]},
     {temp_3[31:0]},
     {temp_1[31:0]},
     {temp[31:0]},
     {temp_4[31:0]},
     {temp_2[31:0]},
     {_io_out_T_2},
     {_io_out_T_1}};	// src/main/scala/gba/cpu/Alu.scala:67:22, :69:14, :72:{14,17}, :75:23, :76:14, :81:31, :82:14, :87:23, :88:14, :93:31, :94:14, :99:23, :100:14, :105:31, :106:14, :111:{14,22}, :114:{14,22}, :117:{14,22}, :120:{22,25}
  assign io_out_0 = _GEN_8[io_opcode];	// src/main/scala/gba/cpu/Alu.scala:67:22, :69:14, :72:14, :76:14, :82:14, :88:14, :94:14, :100:14, :106:14, :111:14, :114:14, :117:14
  assign io_out = io_out_0;	// src/main/scala/gba/cpu/Alu.scala:41:7, :67:22, :69:14
  assign io_flagOut_n = io_out_0[31];	// src/main/scala/gba/cpu/Alu.scala:41:7, :61:25, :67:22, :69:14
  assign io_flagOut_z = io_out_0 == 32'h0;	// src/main/scala/gba/cpu/Alu.scala:41:7, :62:26, :67:22, :69:14
  assign io_flagOut_c =
    _GEN_7
      ? io_shifterCarry
      : _GEN
          ? temp[32]
          : _GEN_2
              ? temp_1[32]
              : _GEN_3
                  ? ~(temp_2[32])
                  : _GEN_4
                      ? ~(temp_3[32])
                      : _GEN_5 ? ~(temp_4[32]) : _GEN_6 ? ~(temp_5[32]) : io_shifterCarry;	// src/main/scala/gba/cpu/Alu.scala:41:7, :63:16, :67:22, :75:23, :77:{20,27}, :81:31, :83:{20,27}, :87:23, :89:{20,23,28}, :93:31, :95:{20,23,28}, :99:23, :101:{20,23,28}, :105:31, :107:{20,23,28}
  assign io_flagOut_v =
    _GEN_7
      ? io_flagIn_v
      : _GEN
          ? (io_a[31] ^ ~(io_b[31])) & (io_a[31] ^ io_out_0[31])
          : _GEN_2
              ? (io_a[31] ^ ~(io_b[31])) & (io_a[31] ^ io_out_0[31])
              : _GEN_3
                  ? (io_a[31] ^ io_b[31]) & (io_a[31] ^ io_out_0[31])
                  : _GEN_4
                      ? (io_a[31] ^ io_b[31]) & (io_a[31] ^ io_out_0[31])
                      : _GEN_5
                          ? (io_a[31] ^ io_b[31]) & (io_b[31] ^ io_out_0[31])
                          : _GEN_6
                              ? (io_a[31] ^ io_b[31]) & (io_b[31] ^ io_out_0[31])
                              : io_flagIn_v;	// src/main/scala/gba/cpu/Alu.scala:41:7, :61:25, :63:16, :64:16, :67:22, :69:14, :78:{20,23,29,40,46,59}, :84:{20,23,29,40,46,59}, :90:{20,28,33,39,45,58}, :96:{20,28,33,39,45,58}, :102:{20,28,33,39,45,58}, :108:{20,28,33,39,45,58}
endmodule

