// Generated by CIRCT firtool-1.62.0
module ARM7TDMI(	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7
  input         clock,	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7
                reset,	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7
                io_enable,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output [31:0] io_debug_registers_0,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_1,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_2,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_3,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_4,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_5,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_6,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_7,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_8,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_9,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_10,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_11,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_12,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_13,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_14,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_registers_15,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_debug_cpsr,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  input         io_mem_CLKEN,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output        io_mem_WRITE,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output [1:0]  io_mem_SIZE,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output        io_mem_PROT_privileged,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_mem_PROT_data,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_mem_LOCK,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output [31:0] io_mem_ADDR,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output        io_mem_MREQ,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_mem_SEQ,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  input         io_mem_ABORT,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  output [31:0] io_mem_WDATA,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  input  [31:0] io_mem_RDATA,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
  input         io_FIQ,	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
                io_IRQ	// src/main/scala/gba/cpu/ARM7TDMI.scala:11:14
);

  wire [31:0]       readData;	// src/main/scala/gba/cpu/ARM7TDMI.scala:288:53, :289:16, :295:64
  wire [31:0]       aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:216:10, :217:31, :218:12
  wire [31:0]       _multiplier_io_outLo;	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
  wire [31:0]       _multiplier_io_outHi;	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
  wire              _multiplier_io_done;	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
  wire              _multiplier_io_outFlagZ;	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
  wire              _multiplier_io_outFlagN;	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
  wire [31:0]       _alu_io_out;	// src/main/scala/gba/cpu/ARM7TDMI.scala:207:19
  wire              _alu_io_flagOut_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:207:19
  wire              _alu_io_flagOut_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:207:19
  wire              _alu_io_flagOut_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:207:19
  wire              _alu_io_flagOut_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:207:19
  wire [31:0]       _shifter_io_out;	// src/main/scala/gba/cpu/ARM7TDMI.scala:198:23
  wire              _shifter_io_carryOut;	// src/main/scala/gba/cpu/ARM7TDMI.scala:198:23
  wire              _controlUnit_io_signals_advancePipeline;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_flushPipeline;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_startException;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_pcNext;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [2:0]        _controlUnit_io_signals_addressSource;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [4:0]        _controlUnit_io_signals_regBankMode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [3:0]        _controlUnit_io_signals_regReadA;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [3:0]        _controlUnit_io_signals_regReadB;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [3:0]        _controlUnit_io_signals_regReadC;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [3:0]        _controlUnit_io_signals_regWriteIndex;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_regWriteEnable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_regUserReadC;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_regUserWrite;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_cpsrUpdateCond;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_cpsrUpdateThumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [1:0]        _controlUnit_io_signals_cpsrUpdateFields;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [1:0]        _controlUnit_io_signals_spsrUpdateFields;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_cpsrRestore;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_cpsrFromMultiply;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [2:0]        _controlUnit_io_signals_busB;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [31:0]       _controlUnit_io_signals_immediate;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [3:0]        _controlUnit_io_signals_aluOpcode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_aluOutAlign4;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_aluInAAlign4;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [2:0]        _controlUnit_io_signals_shiftKind;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [5:0]        _controlUnit_io_signals_shiftImmediate;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_shiftDoLatch;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_shiftUseLatched;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_shiftByAddressAlign;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_multiplyEnable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_multiplySigned;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_multiplyLoadAccumulator;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_multiplyAccumulate;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_multiplyLong;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [1:0]        _controlUnit_io_signals_memWidth;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_latchMemReadData;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_memReadDataSigned;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire              _controlUnit_io_signals_incrementerForceWord;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  wire [3:0]        _decodeUnit_io_decoded_kind;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [3:0]        _decodeUnit_io_decoded_condition;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [3:0]        _decodeUnit_io_decoded_regN;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [3:0]        _decodeUnit_io_decoded_regD;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [3:0]        _decodeUnit_io_decoded_regS;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [3:0]        _decodeUnit_io_decoded_regM;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [23:0]       _decodeUnit_io_decoded_immediate;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [3:0]        _decodeUnit_io_decoded_opcode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire [6:0]        _decodeUnit_io_decoded_flags;	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
  wire              enable = io_enable & io_mem_CLKEN;	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
  reg  [31:0]       memAddrReg;	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23
  reg  [31:0]       memReadDataReg;	// src/main/scala/gba/cpu/ARM7TDMI.scala:30:27
  reg  [30:0][31:0] registers;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26
  reg               cpsr_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               cpsr_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               cpsr_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               cpsr_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg  [19:0]       cpsr_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               cpsr_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               cpsr_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               cpsr_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg  [4:0]        cpsr_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
  reg               spsrVec_0_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_0_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_0_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_0_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [19:0]       spsrVec_0_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_0_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_0_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_0_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [4:0]        spsrVec_0_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [19:0]       spsrVec_1_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_1_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [4:0]        spsrVec_1_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [19:0]       spsrVec_2_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_2_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [4:0]        spsrVec_2_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [19:0]       spsrVec_3_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_3_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [4:0]        spsrVec_3_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [19:0]       spsrVec_4_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg               spsrVec_4_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  reg  [4:0]        spsrVec_4_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20
  wire [2:0]        spsrIndex =
    _controlUnit_io_signals_regBankMode == 5'h11
      ? 3'h4
      : {1'h0,
         _controlUnit_io_signals_regBankMode == 5'h12
           ? 2'h3
           : _controlUnit_io_signals_regBankMode == 5'h1B
               ? 2'h2
               : {1'h0, _controlUnit_io_signals_regBankMode == 5'h17}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :103:54, :138:17
  wire              modeHasSpsr =
    _controlUnit_io_signals_regBankMode != 5'h10
    & _controlUnit_io_signals_regBankMode != 5'h1F;	// <stdin>:4363:30, src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :111:{42,60,84}, :138:17
  wire              _bBus_T = _controlUnit_io_signals_regBankMode == 5'h11;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :73:16, :138:17
  wire [31:0][31:0] _GEN = {{1{registers[5'h0]}}, registers};	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :120:8, :138:17
  wire [31:0]       aBus =
    _GEN[{1'h0, _controlUnit_io_signals_regReadA}
    + (_bBus_T & _controlUnit_io_signals_regReadA[3]
       & _controlUnit_io_signals_regReadA != 4'hF
         ? 5'h10
         : _controlUnit_io_signals_regReadA == 4'hD
           | _controlUnit_io_signals_regReadA == 4'hE
             ? (_controlUnit_io_signals_regBankMode == 5'h13
                  ? 5'h3
                  : _controlUnit_io_signals_regBankMode == 5'h17
                      ? 5'h5
                      : _controlUnit_io_signals_regBankMode == 5'h1B
                          ? 5'h7
                          : _controlUnit_io_signals_regBankMode == 5'h12 ? 5'h9 : 5'h0)
             : 5'h0)];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :72:29, :73:{16,41,48,57,66}, :74:14, :75:{24,33,42,52}, :76:{18,42}, :77:16, :78:{25,44}, :79:16, :80:{25,48}, :81:16, :82:{25,42}, :83:16, :86:11, :120:8, :138:17
  wire [7:0]        _GEN_0 =
    {{spsrVec_0_cond_n},
     {spsrVec_0_cond_n},
     {spsrVec_0_cond_n},
     {spsrVec_4_cond_n},
     {spsrVec_3_cond_n},
     {spsrVec_2_cond_n},
     {spsrVec_1_cond_n},
     {spsrVec_0_cond_n}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0]        _GEN_1 =
    {{spsrVec_0_cond_z},
     {spsrVec_0_cond_z},
     {spsrVec_0_cond_z},
     {spsrVec_4_cond_z},
     {spsrVec_3_cond_z},
     {spsrVec_2_cond_z},
     {spsrVec_1_cond_z},
     {spsrVec_0_cond_z}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0]        _GEN_2 =
    {{spsrVec_0_cond_c},
     {spsrVec_0_cond_c},
     {spsrVec_0_cond_c},
     {spsrVec_4_cond_c},
     {spsrVec_3_cond_c},
     {spsrVec_2_cond_c},
     {spsrVec_1_cond_c},
     {spsrVec_0_cond_c}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0]        _GEN_3 =
    {{spsrVec_0_cond_v},
     {spsrVec_0_cond_v},
     {spsrVec_0_cond_v},
     {spsrVec_4_cond_v},
     {spsrVec_3_cond_v},
     {spsrVec_2_cond_v},
     {spsrVec_1_cond_v},
     {spsrVec_0_cond_v}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0][19:0]  _GEN_4 =
    {{spsrVec_0_padding},
     {spsrVec_0_padding},
     {spsrVec_0_padding},
     {spsrVec_4_padding},
     {spsrVec_3_padding},
     {spsrVec_2_padding},
     {spsrVec_1_padding},
     {spsrVec_0_padding}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0]        _GEN_5 =
    {{spsrVec_0_irqDisable},
     {spsrVec_0_irqDisable},
     {spsrVec_0_irqDisable},
     {spsrVec_4_irqDisable},
     {spsrVec_3_irqDisable},
     {spsrVec_2_irqDisable},
     {spsrVec_1_irqDisable},
     {spsrVec_0_irqDisable}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0]        _GEN_6 =
    {{spsrVec_0_fiqDisable},
     {spsrVec_0_fiqDisable},
     {spsrVec_0_fiqDisable},
     {spsrVec_4_fiqDisable},
     {spsrVec_3_fiqDisable},
     {spsrVec_2_fiqDisable},
     {spsrVec_1_fiqDisable},
     {spsrVec_0_fiqDisable}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0]        _GEN_7 =
    {{spsrVec_0_thumb},
     {spsrVec_0_thumb},
     {spsrVec_0_thumb},
     {spsrVec_4_thumb},
     {spsrVec_3_thumb},
     {spsrVec_2_thumb},
     {spsrVec_1_thumb},
     {spsrVec_0_thumb}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [7:0][4:0]   _GEN_8 =
    {{spsrVec_0_mode},
     {spsrVec_0_mode},
     {spsrVec_0_mode},
     {spsrVec_4_mode},
     {spsrVec_3_mode},
     {spsrVec_2_mode},
     {spsrVec_1_mode},
     {spsrVec_0_mode}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :127:20
  wire [4:0]        _cBus_T =
    _controlUnit_io_signals_regUserReadC ? 5'h10 : _controlUnit_io_signals_regBankMode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :136:10, :138:17
  wire [31:0]       cBus =
    _GEN[{1'h0, _controlUnit_io_signals_regReadC}
    + (_cBus_T == 5'h11 & _controlUnit_io_signals_regReadC[3]
       & _controlUnit_io_signals_regReadC != 4'hF
         ? 5'h10
         : _controlUnit_io_signals_regReadC == 4'hD
           | _controlUnit_io_signals_regReadC == 4'hE
             ? (_cBus_T == 5'h13
                  ? 5'h3
                  : _cBus_T == 5'h17
                      ? 5'h5
                      : _cBus_T == 5'h1B ? 5'h7 : _cBus_T == 5'h12 ? 5'h9 : 5'h0)
             : 5'h0)];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :72:29, :73:{16,41,48,57,66}, :74:14, :75:{24,33,42,52}, :76:{18,42}, :77:16, :78:{25,44}, :79:16, :80:{25,48}, :81:16, :82:{25,42}, :83:16, :86:11, :120:8, :133:8, :136:10, :138:17
  wire              _GEN_9 =
    _controlUnit_io_signals_cpsrUpdateFields[0] & cpsr_mode != 5'h10;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :89:21, :112:34, :138:17, :155:{35,39}
  wire              _GEN_10 = _controlUnit_io_signals_cpsrRestore & modeHasSpsr;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :111:60, :173:31
  wire              _GEN_11 =
    ~_controlUnit_io_signals_startException
    & (_GEN_10
         ? _GEN_7[spsrIndex]
         : _GEN_9
             ? aluBus[5]
             : _controlUnit_io_signals_cpsrUpdateThumb ? aBus[0] : cpsr_thumb);	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :89:21, :103:54, :113:29, :120:8, :127:20, :152:36, :153:{22,29}, :155:{39,58}, :157:{22,31}, :173:{31,47}, :174:16, :176:35, :179:22, :216:10, :217:31, :218:12
  assign aluBus =
    ({32{~_controlUnit_io_signals_aluOutAlign4}} | 32'hFFFFFFFC) & _alu_io_out;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :207:19, :210:22, :216:10, :217:31, :218:12
  wire [31:0]       _incrementerBus_T_3 =
    memAddrReg
    + {29'h0, cpsr_thumb & ~_controlUnit_io_signals_incrementerForceWord ? 3'h2 : 3'h4};	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23, :53:27, :89:21, :103:54, :165:17, :244:{32,37,52,55}
  reg  [1:0]        currentMemReadWidth;	// src/main/scala/gba/cpu/ARM7TDMI.scala:247:32
  reg  [1:0]        lastMemReadWidth;	// src/main/scala/gba/cpu/ARM7TDMI.scala:248:29
  reg  [1:0]        lastMemReadAlign;	// src/main/scala/gba/cpu/ARM7TDMI.scala:249:29
  wire              _GEN_12 = _controlUnit_io_signals_addressSource == 3'h1;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :251:34
  wire              _GEN_13 = _controlUnit_io_signals_addressSource == 3'h2;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :251:34
  wire              _GEN_14 = _controlUnit_io_signals_addressSource == 3'h3;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :251:34
  wire              _GEN_15 = _controlUnit_io_signals_addressSource == 3'h4;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :103:54, :251:34
  wire [7:0][31:0]  _GEN_16 =
    {{_controlUnit_io_signals_immediate},
     {_multiplier_io_outHi},
     {_multiplier_io_outLo},
     {modeHasSpsr
        ? {_GEN_0[spsrIndex],
           _GEN_1[spsrIndex],
           _GEN_2[spsrIndex],
           _GEN_3[spsrIndex],
           _GEN_4[spsrIndex],
           _GEN_5[spsrIndex],
           _GEN_6[spsrIndex],
           _GEN_7[spsrIndex],
           _GEN_8[spsrIndex]}
        : {cpsr_cond_n,
           cpsr_cond_z,
           cpsr_cond_c,
           cpsr_cond_v,
           cpsr_padding,
           cpsr_irqDisable,
           cpsr_fiqDisable,
           cpsr_thumb,
           cpsr_mode}},
     {{cpsr_cond_n,
       cpsr_cond_z,
       cpsr_cond_c,
       cpsr_cond_v,
       cpsr_padding,
       cpsr_irqDisable,
       cpsr_fiqDisable,
       cpsr_thumb,
       cpsr_mode}},
     {readData},
     {_controlUnit_io_signals_immediate},
     {_GEN[{1'h0, _controlUnit_io_signals_regReadB}
        + (_bBus_T & _controlUnit_io_signals_regReadB[3]
           & _controlUnit_io_signals_regReadB != 4'hF
             ? 5'h10
             : _controlUnit_io_signals_regReadB == 4'hD
               | _controlUnit_io_signals_regReadB == 4'hE
                 ? (_controlUnit_io_signals_regBankMode == 5'h13
                      ? 5'h3
                      : _controlUnit_io_signals_regBankMode == 5'h17
                          ? 5'h5
                          : _controlUnit_io_signals_regBankMode == 5'h1B
                              ? 5'h7
                              : _controlUnit_io_signals_regBankMode == 5'h12
                                  ? 5'h9
                                  : 5'h0)
                 : 5'h0)]}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :59:47, :72:29, :73:{16,41,48,57,66}, :74:14, :75:{24,33,42,52}, :76:{18,42}, :77:16, :78:{25,44}, :79:16, :80:{25,48}, :81:16, :82:{25,42}, :83:16, :86:11, :89:21, :103:54, :111:60, :120:8, :121:{22,47}, :122:10, :123:{29,49}, :124:{10,18}, :125:{29,49}, :126:24, :127:{12,20}, :130:{12,20}, :138:17, :223:26, :232:{22,48}, :233:10, :234:{29,55}, :235:10, :274:{22,49}, :276:10, :288:53, :289:16, :295:64
  wire [31:0]       bBus = _GEN_16[_controlUnit_io_signals_busB];	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :59:47, :121:{22,47}, :122:10, :123:{29,49}, :124:10, :125:{29,49}, :126:24, :232:{22,48}, :233:10, :234:{29,55}, :235:10, :274:{22,49}, :276:10
  wire [31:0]       _maskValue_T_1 =
    memReadDataReg
    >> {27'h0,
        lastMemReadWidth == 2'h1 ? {lastMemReadAlign[1], 1'h1} : lastMemReadAlign,
        3'h7};	// src/main/scala/gba/cpu/ARM7TDMI.scala:30:27, :59:22, :248:29, :249:29, :269:36, :281:25, :282:26, :283:26, :286:{42,46}
  wire [7:0]        maskValue =
    {8{_controlUnit_io_signals_memReadDataSigned & _maskValue_T_1[0]}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :279:32, :280:38, :286:{17,24,42}
  wire [15:0]       _readData_T_20 = {2{maskValue}};	// src/main/scala/gba/cpu/ARM7TDMI.scala:279:32, :280:38, :286:{17,24}, :297:62
  assign readData =
    lastMemReadWidth == 2'h0
      ? {(&lastMemReadAlign) ? memReadDataReg[31:24] : maskValue,
         lastMemReadAlign == 2'h2 ? memReadDataReg[23:16] : maskValue,
         lastMemReadAlign == 2'h1 ? memReadDataReg[15:8] : maskValue,
         lastMemReadAlign == 2'h0 ? memReadDataReg[7:0] : maskValue}
      : lastMemReadWidth == 2'h1
          ? {lastMemReadAlign[1] ? memReadDataReg[31:16] : _readData_T_20,
             lastMemReadAlign[1] ? _readData_T_20 : memReadDataReg[15:0]}
          : memReadDataReg;	// src/main/scala/gba/cpu/ARM7TDMI.scala:30:27, :86:11, :103:54, :248:29, :249:29, :269:36, :275:31, :279:32, :280:38, :286:{17,24}, :288:{28,53}, :289:{16,22}, :290:{12,30,53}, :291:{12,30,53}, :292:{12,30,53}, :293:{12,30,53}, :295:{35,64}, :296:{16,22}, :297:{12,29,48,62}, :298:{12,49}
  wire [4:0]        _GEN_17 = {_bBus_T, 4'h0};	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :73:16, :86:11
  wire [4:0]        offset_15 =
    _bBus_T
      ? 5'h10
      : _controlUnit_io_signals_regBankMode == 5'h13
          ? 5'h3
          : _controlUnit_io_signals_regBankMode == 5'h17
              ? 5'h5
              : _controlUnit_io_signals_regBankMode == 5'h1B
                  ? 5'h7
                  : _controlUnit_io_signals_regBankMode == 5'h12 ? 5'h9 : 5'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :72:29, :73:{16,66}, :74:14, :75:52, :76:{18,42}, :77:16, :78:{25,44}, :79:16, :80:{25,48}, :81:16, :82:{25,42}, :83:16, :138:17
  always @(posedge clock) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7
    automatic logic _GEN_18;	// src/main/scala/gba/cpu/ARM7TDMI.scala:165:17
    automatic logic _GEN_19;	// src/main/scala/gba/cpu/ARM7TDMI.scala:165:17
    automatic logic _GEN_20;	// src/main/scala/gba/cpu/ARM7TDMI.scala:165:17
    automatic logic _GEN_21;	// src/main/scala/gba/cpu/ARM7TDMI.scala:165:17
    automatic logic _GEN_22;	// src/main/scala/gba/cpu/ARM7TDMI.scala:165:17
    automatic logic _GEN_23;	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
    automatic logic _GEN_24;	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
    automatic logic _GEN_25;	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
    automatic logic _GEN_26;	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
    automatic logic _GEN_27;	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
    _GEN_18 = spsrIndex == 3'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:103:54, :121:22, :165:17
    _GEN_19 = spsrIndex == 3'h1;	// src/main/scala/gba/cpu/ARM7TDMI.scala:103:54, :165:17
    _GEN_20 = spsrIndex == 3'h2;	// src/main/scala/gba/cpu/ARM7TDMI.scala:103:54, :165:17
    _GEN_21 = spsrIndex == 3'h3;	// src/main/scala/gba/cpu/ARM7TDMI.scala:103:54, :165:17
    _GEN_22 = spsrIndex == 3'h4;	// src/main/scala/gba/cpu/ARM7TDMI.scala:103:54, :165:17
    _GEN_23 = _controlUnit_io_signals_startException & _GEN_18;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :170:55, :176:35, :184:12
    _GEN_24 = _controlUnit_io_signals_startException & _GEN_19;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :170:55, :176:35, :184:12
    _GEN_25 = _controlUnit_io_signals_startException & _GEN_20;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :170:55, :176:35, :184:12
    _GEN_26 = _controlUnit_io_signals_startException & _GEN_21;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :170:55, :176:35, :184:12
    _GEN_27 = _controlUnit_io_signals_startException & _GEN_22;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :165:17, :170:55, :176:35, :184:12
    if (enable) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
      automatic logic _GEN_28;	// src/main/scala/gba/cpu/ARM7TDMI.scala:164:39
      automatic logic _GEN_29;	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:39
      _GEN_28 = _controlUnit_io_signals_spsrUpdateFields[0] & modeHasSpsr;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :111:60, :164:{35,39}
      _GEN_29 = _controlUnit_io_signals_spsrUpdateFields[1] & modeHasSpsr;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :111:60, :170:{35,39}
      if (_GEN_12)	// src/main/scala/gba/cpu/ARM7TDMI.scala:251:34
        memAddrReg <= _incrementerBus_T_3;	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23, :244:32
      else if (_GEN_13)	// src/main/scala/gba/cpu/ARM7TDMI.scala:251:34
        memAddrReg <= registers[5'hF];	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23, :70:26, :138:17
      else if (_GEN_14)	// src/main/scala/gba/cpu/ARM7TDMI.scala:251:34
        memAddrReg <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23, :216:10, :217:31, :218:12
      else if (_GEN_15)	// src/main/scala/gba/cpu/ARM7TDMI.scala:251:34
        memAddrReg <= _controlUnit_io_signals_immediate;	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23, :53:27
      if (_GEN_23) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        spsrVec_0_cond_n <= cpsr_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_cond_z <= cpsr_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_cond_c <= cpsr_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_cond_v <= cpsr_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_irqDisable <= cpsr_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_fiqDisable <= cpsr_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_thumb <= cpsr_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_0_mode <= cpsr_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
      end
      else begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        if (_GEN_29 & _GEN_18) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:17, :170:{39,55}, :171:17
          spsrVec_0_cond_n <= aluBus[31];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_0_cond_z <= aluBus[30];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_0_cond_c <= aluBus[29];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_0_cond_v <= aluBus[28];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
        end
        if (_GEN_28 & _GEN_18) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :164:{39,55}, :165:17
          spsrVec_0_irqDisable <= aluBus[7];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :168:32, :216:10, :217:31, :218:12
          spsrVec_0_fiqDisable <= aluBus[6];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :167:32, :216:10, :217:31, :218:12
          spsrVec_0_thumb <= aluBus[5];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :166:27, :216:10, :217:31, :218:12
          spsrVec_0_mode <= aluBus[4:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:52, :216:10, :217:31, :218:12
        end
      end
      if (_GEN_24) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        spsrVec_1_cond_n <= cpsr_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_cond_z <= cpsr_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_cond_c <= cpsr_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_cond_v <= cpsr_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_irqDisable <= cpsr_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_fiqDisable <= cpsr_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_thumb <= cpsr_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_1_mode <= cpsr_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
      end
      else begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        if (_GEN_29 & _GEN_19) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:17, :170:{39,55}, :171:17
          spsrVec_1_cond_n <= aluBus[31];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_1_cond_z <= aluBus[30];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_1_cond_c <= aluBus[29];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_1_cond_v <= aluBus[28];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
        end
        if (_GEN_28 & _GEN_19) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :164:{39,55}, :165:17
          spsrVec_1_irqDisable <= aluBus[7];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :168:32, :216:10, :217:31, :218:12
          spsrVec_1_fiqDisable <= aluBus[6];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :167:32, :216:10, :217:31, :218:12
          spsrVec_1_thumb <= aluBus[5];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :166:27, :216:10, :217:31, :218:12
          spsrVec_1_mode <= aluBus[4:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:52, :216:10, :217:31, :218:12
        end
      end
      if (_GEN_25) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        spsrVec_2_cond_n <= cpsr_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_cond_z <= cpsr_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_cond_c <= cpsr_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_cond_v <= cpsr_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_irqDisable <= cpsr_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_fiqDisable <= cpsr_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_thumb <= cpsr_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_2_mode <= cpsr_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
      end
      else begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        if (_GEN_29 & _GEN_20) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:17, :170:{39,55}, :171:17
          spsrVec_2_cond_n <= aluBus[31];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_2_cond_z <= aluBus[30];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_2_cond_c <= aluBus[29];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_2_cond_v <= aluBus[28];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
        end
        if (_GEN_28 & _GEN_20) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :164:{39,55}, :165:17
          spsrVec_2_irqDisable <= aluBus[7];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :168:32, :216:10, :217:31, :218:12
          spsrVec_2_fiqDisable <= aluBus[6];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :167:32, :216:10, :217:31, :218:12
          spsrVec_2_thumb <= aluBus[5];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :166:27, :216:10, :217:31, :218:12
          spsrVec_2_mode <= aluBus[4:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:52, :216:10, :217:31, :218:12
        end
      end
      if (_GEN_26) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        spsrVec_3_cond_n <= cpsr_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_cond_z <= cpsr_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_cond_c <= cpsr_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_cond_v <= cpsr_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_irqDisable <= cpsr_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_fiqDisable <= cpsr_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_thumb <= cpsr_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_3_mode <= cpsr_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
      end
      else begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        if (_GEN_29 & _GEN_21) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:17, :170:{39,55}, :171:17
          spsrVec_3_cond_n <= aluBus[31];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_3_cond_z <= aluBus[30];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_3_cond_c <= aluBus[29];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_3_cond_v <= aluBus[28];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
        end
        if (_GEN_28 & _GEN_21) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :164:{39,55}, :165:17
          spsrVec_3_irqDisable <= aluBus[7];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :168:32, :216:10, :217:31, :218:12
          spsrVec_3_fiqDisable <= aluBus[6];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :167:32, :216:10, :217:31, :218:12
          spsrVec_3_thumb <= aluBus[5];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :166:27, :216:10, :217:31, :218:12
          spsrVec_3_mode <= aluBus[4:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:52, :216:10, :217:31, :218:12
        end
      end
      if (_GEN_27) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        spsrVec_4_cond_n <= cpsr_cond_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_cond_z <= cpsr_cond_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_cond_c <= cpsr_cond_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_cond_v <= cpsr_cond_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_irqDisable <= cpsr_irqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_fiqDisable <= cpsr_fiqDisable;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_thumb <= cpsr_thumb;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
        spsrVec_4_mode <= cpsr_mode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
      end
      else begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:170:55, :176:35, :184:12
        if (_GEN_29 & _GEN_22) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:17, :170:{39,55}, :171:17
          spsrVec_4_cond_n <= aluBus[31];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_4_cond_z <= aluBus[30];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_4_cond_c <= aluBus[29];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
          spsrVec_4_cond_v <= aluBus[28];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :171:43, :216:10, :217:31, :218:12
        end
        if (_GEN_28 & _GEN_22) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :164:{39,55}, :165:17
          spsrVec_4_irqDisable <= aluBus[7];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :168:32, :216:10, :217:31, :218:12
          spsrVec_4_fiqDisable <= aluBus[6];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :167:32, :216:10, :217:31, :218:12
          spsrVec_4_thumb <= aluBus[5];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :166:27, :216:10, :217:31, :218:12
          spsrVec_4_mode <= aluBus[4:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:102:20, :165:52, :216:10, :217:31, :218:12
        end
      end
      currentMemReadWidth <= _controlUnit_io_signals_memWidth;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :247:32
    end
    if (enable & _controlUnit_io_signals_latchMemReadData) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :248:29, :257:17, :260:37, :261:24
      memReadDataReg <= io_mem_RDATA;	// src/main/scala/gba/cpu/ARM7TDMI.scala:30:27
      lastMemReadWidth <= currentMemReadWidth;	// src/main/scala/gba/cpu/ARM7TDMI.scala:247:32, :248:29
      lastMemReadAlign <= memAddrReg[1:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23, :249:29, :262:37
    end
    if (enable & _GEN_23)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :102:20, :138:17, :170:55, :176:35, :184:12
      spsrVec_0_padding <= cpsr_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
    if (enable & _GEN_24)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :102:20, :138:17, :170:55, :176:35, :184:12
      spsrVec_1_padding <= cpsr_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
    if (enable & _GEN_25)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :102:20, :138:17, :170:55, :176:35, :184:12
      spsrVec_2_padding <= cpsr_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
    if (enable & _GEN_26)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :102:20, :138:17, :170:55, :176:35, :184:12
      spsrVec_3_padding <= cpsr_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
    if (enable & _GEN_27)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :102:20, :138:17, :170:55, :176:35, :184:12
      spsrVec_4_padding <= cpsr_padding;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :102:20
    if (reset) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7
      registers <=
        '{32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0,
          32'h0};	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:{26,43}
      cpsr_cond_n <= 1'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :89:21
      cpsr_cond_z <= 1'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :89:21
      cpsr_cond_c <= 1'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :89:21
      cpsr_cond_v <= 1'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :89:21
      cpsr_padding <= 20'h0;	// <stdin>:4367:33, src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
      cpsr_irqDisable <= 1'h1;	// src/main/scala/gba/cpu/ARM7TDMI.scala:59:22, :89:21
      cpsr_fiqDisable <= 1'h1;	// src/main/scala/gba/cpu/ARM7TDMI.scala:59:22, :89:21
      cpsr_thumb <= 1'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :89:21
      cpsr_mode <= 5'h1F;	// <stdin>:4363:30, src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    end
    else begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7
      automatic logic [4:0] _GEN_30 =
        _controlUnit_io_signals_regUserWrite
          ? 5'h10
          : _controlUnit_io_signals_regBankMode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :138:17, :146:14
      automatic logic [4:0] _GEN_31;	// src/main/scala/gba/cpu/ARM7TDMI.scala:86:11
      _GEN_31 =
        {1'h0, _controlUnit_io_signals_regWriteIndex}
        + (_GEN_30 == 5'h11 & _controlUnit_io_signals_regWriteIndex[3]
           & _controlUnit_io_signals_regWriteIndex != 4'hF
             ? 5'h10
             : _controlUnit_io_signals_regWriteIndex == 4'hD
               | _controlUnit_io_signals_regWriteIndex == 4'hE
                 ? (_GEN_30 == 5'h13
                      ? 5'h3
                      : _GEN_30 == 5'h17
                          ? 5'h5
                          : _GEN_30 == 5'h1B ? 5'h7 : _GEN_30 == 5'h12 ? 5'h9 : 5'h0)
                 : 5'h0);	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :72:29, :73:{16,41,48,57,66}, :74:14, :75:{24,33,42,52}, :76:{18,42}, :77:16, :78:{25,44}, :79:16, :80:{25,48}, :81:16, :82:{25,42}, :83:16, :86:11, :138:17, :146:14
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h0)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h0] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h1)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h1] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h2)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h2] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h3)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h3] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h4)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h4] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h5)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h5] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h6)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h6] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h7)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h7] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h8)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h8] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h9)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h9] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'hA)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'hA] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'hB)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'hB] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'hC)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'hC] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'hD)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'hD] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'hE)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'hE] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
        if (_controlUnit_io_signals_pcNext)	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
          registers[5'hF] <= {_incrementerBus_T_3[31:1], 1'h0};	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :70:26, :138:17, :191:30, :244:32
        else if (_controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'hF)	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :70:26, :86:11, :138:17, :139:35, :147:12
          registers[5'hF] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
        if (_controlUnit_io_signals_cpsrFromMultiply) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
          cpsr_cond_n <= _multiplier_io_outFlagN;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :223:26
          cpsr_cond_z <= _multiplier_io_outFlagZ;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :223:26
        end
        else if (enable) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
          if (_GEN_10) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:173:31
            cpsr_cond_n <= _GEN_0[spsrIndex];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :103:54, :127:20
            cpsr_cond_z <= _GEN_1[spsrIndex];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :103:54, :127:20
          end
          else if (_controlUnit_io_signals_cpsrUpdateFields[1]) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :161:35
            cpsr_cond_n <= aluBus[31];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :162:47, :216:10, :217:31, :218:12
            cpsr_cond_z <= aluBus[30];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :162:47, :216:10, :217:31, :218:12
          end
          else if (_controlUnit_io_signals_cpsrUpdateCond) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
            cpsr_cond_n <= _alu_io_flagOut_n;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :207:19
            cpsr_cond_z <= _alu_io_flagOut_z;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :207:19
          end
        end
        if (_GEN_10) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:173:31
          cpsr_cond_c <= _GEN_2[spsrIndex];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :103:54, :127:20
          cpsr_cond_v <= _GEN_3[spsrIndex];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :103:54, :127:20
        end
        else if (_controlUnit_io_signals_cpsrUpdateFields[1]) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :161:35
          cpsr_cond_c <= aluBus[29];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :162:47, :216:10, :217:31, :218:12
          cpsr_cond_v <= aluBus[28];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :162:47, :216:10, :217:31, :218:12
        end
        else if (_controlUnit_io_signals_cpsrUpdateCond) begin	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
          cpsr_cond_c <= _alu_io_flagOut_c;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :207:19
          cpsr_cond_v <= _alu_io_flagOut_v;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :207:19
        end
        cpsr_irqDisable <=
          _controlUnit_io_signals_startException
          | (_GEN_10 ? _GEN_5[spsrIndex] : _GEN_9 ? aluBus[7] : cpsr_irqDisable);	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :89:21, :103:54, :113:29, :127:20, :155:{39,58}, :159:{27,36}, :173:{31,47}, :174:16, :176:35, :180:27, :216:10, :217:31, :218:12
        cpsr_fiqDisable <=
          _controlUnit_io_signals_startException & _bBus_T
          | (_GEN_10 ? _GEN_6[spsrIndex] : _GEN_9 ? aluBus[6] : cpsr_fiqDisable);	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :73:16, :89:21, :103:54, :113:29, :127:20, :155:{39,58}, :158:{27,36}, :173:{31,47}, :174:16, :176:35, :181:38, :182:29, :216:10, :217:31, :218:12
        cpsr_thumb <= _GEN_11;	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :173:47, :176:35, :179:22
        if (_controlUnit_io_signals_startException)	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
          cpsr_mode <= _controlUnit_io_signals_regBankMode;	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :89:21
        else if (_GEN_10)	// src/main/scala/gba/cpu/ARM7TDMI.scala:173:31
          cpsr_mode <= _GEN_8[spsrIndex];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :103:54, :127:20
        else if (_GEN_9)	// src/main/scala/gba/cpu/ARM7TDMI.scala:155:39
          cpsr_mode <= aluBus[4:0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :156:56, :216:10, :217:31, :218:12
      end
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h10)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h10] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h11)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h11] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h12)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h12] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h13)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h13] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h14)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h14] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h15)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h15] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h16)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h16] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h17)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h17] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h18)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h18] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h19)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h19] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h1A)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h1A] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h1B)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h1B] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h1C)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h1C] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h1D)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h1D] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _controlUnit_io_signals_regWriteEnable & _GEN_31 == 5'h1E)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :70:26, :86:11, :138:17, :139:35, :147:12
        registers[5'h1E] <= aluBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:70:26, :138:17, :216:10, :217:31, :218:12
      if (enable & _GEN_10)	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :89:21, :138:17, :173:31, :194:10
        cpsr_padding <= _GEN_4[spsrIndex];	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21, :103:54, :127:20
    end
  end // always @(posedge)
  Decoder decodeUnit (	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .clock                (clock),
    .reset                (reset),
    .io_enable            (enable),	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
    .io_thumb             (cpsr_thumb),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_advancePipeline   (_controlUnit_io_signals_advancePipeline),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_flushPipeline     (_controlUnit_io_signals_flushPipeline),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_readData          (io_mem_RDATA),
    .io_readAddress       (memAddrReg),	// src/main/scala/gba/cpu/ARM7TDMI.scala:29:23
    .io_decoded_kind      (_decodeUnit_io_decoded_kind),
    .io_decoded_condition (_decodeUnit_io_decoded_condition),
    .io_decoded_regN      (_decodeUnit_io_decoded_regN),
    .io_decoded_regD      (_decodeUnit_io_decoded_regD),
    .io_decoded_regS      (_decodeUnit_io_decoded_regS),
    .io_decoded_regM      (_decodeUnit_io_decoded_regM),
    .io_decoded_immediate (_decodeUnit_io_decoded_immediate),
    .io_decoded_opcode    (_decodeUnit_io_decoded_opcode),
    .io_decoded_flags     (_decodeUnit_io_decoded_flags)
  );
  Control controlUnit (	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .clock                              (clock),
    .reset                              (reset),
    .io_enable                          (enable),	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
    .io_signals_advancePipeline         (_controlUnit_io_signals_advancePipeline),
    .io_signals_flushPipeline           (_controlUnit_io_signals_flushPipeline),
    .io_signals_startException          (_controlUnit_io_signals_startException),
    .io_signals_pcNext                  (_controlUnit_io_signals_pcNext),
    .io_signals_addressSource           (_controlUnit_io_signals_addressSource),
    .io_signals_regBankMode             (_controlUnit_io_signals_regBankMode),
    .io_signals_regReadA                (_controlUnit_io_signals_regReadA),
    .io_signals_regReadB                (_controlUnit_io_signals_regReadB),
    .io_signals_regReadC                (_controlUnit_io_signals_regReadC),
    .io_signals_regWriteIndex           (_controlUnit_io_signals_regWriteIndex),
    .io_signals_regWriteEnable          (_controlUnit_io_signals_regWriteEnable),
    .io_signals_regUserReadC            (_controlUnit_io_signals_regUserReadC),
    .io_signals_regUserWrite            (_controlUnit_io_signals_regUserWrite),
    .io_signals_cpsrUpdateCond          (_controlUnit_io_signals_cpsrUpdateCond),
    .io_signals_cpsrUpdateThumb         (_controlUnit_io_signals_cpsrUpdateThumb),
    .io_signals_cpsrUpdateFields        (_controlUnit_io_signals_cpsrUpdateFields),
    .io_signals_spsrUpdateFields        (_controlUnit_io_signals_spsrUpdateFields),
    .io_signals_cpsrRestore             (_controlUnit_io_signals_cpsrRestore),
    .io_signals_cpsrFromMultiply        (_controlUnit_io_signals_cpsrFromMultiply),
    .io_signals_busB                    (_controlUnit_io_signals_busB),
    .io_signals_immediate               (_controlUnit_io_signals_immediate),
    .io_signals_aluOpcode               (_controlUnit_io_signals_aluOpcode),
    .io_signals_aluOutAlign4            (_controlUnit_io_signals_aluOutAlign4),
    .io_signals_aluInAAlign4            (_controlUnit_io_signals_aluInAAlign4),
    .io_signals_shiftKind               (_controlUnit_io_signals_shiftKind),
    .io_signals_shiftImmediate          (_controlUnit_io_signals_shiftImmediate),
    .io_signals_shiftDoLatch            (_controlUnit_io_signals_shiftDoLatch),
    .io_signals_shiftUseLatched         (_controlUnit_io_signals_shiftUseLatched),
    .io_signals_shiftByAddressAlign     (_controlUnit_io_signals_shiftByAddressAlign),
    .io_signals_multiplyEnable          (_controlUnit_io_signals_multiplyEnable),
    .io_signals_multiplySigned          (_controlUnit_io_signals_multiplySigned),
    .io_signals_multiplyLoadAccumulator (_controlUnit_io_signals_multiplyLoadAccumulator),
    .io_signals_multiplyAccumulate      (_controlUnit_io_signals_multiplyAccumulate),
    .io_signals_multiplyLong            (_controlUnit_io_signals_multiplyLong),
    .io_signals_memRequest              (io_mem_MREQ),
    .io_signals_memSequential           (io_mem_SEQ),
    .io_signals_memWrite                (io_mem_WRITE),
    .io_signals_memWidth                (_controlUnit_io_signals_memWidth),
    .io_signals_memProt_data            (io_mem_PROT_data),
    .io_signals_memLock                 (io_mem_LOCK),
    .io_signals_latchMemReadData        (_controlUnit_io_signals_latchMemReadData),
    .io_signals_memReadDataSigned       (_controlUnit_io_signals_memReadDataSigned),
    .io_signals_incrementerForceWord    (_controlUnit_io_signals_incrementerForceWord),
    .io_nextInstruction_kind            (_decodeUnit_io_decoded_kind),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_condition       (_decodeUnit_io_decoded_condition),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_regN            (_decodeUnit_io_decoded_regN),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_regD            (_decodeUnit_io_decoded_regD),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_regS            (_decodeUnit_io_decoded_regS),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_regM            (_decodeUnit_io_decoded_regM),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_immediate       (_decodeUnit_io_decoded_immediate),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_opcode          (_decodeUnit_io_decoded_opcode),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_nextInstruction_flags           (_decodeUnit_io_decoded_flags),	// src/main/scala/gba/cpu/ARM7TDMI.scala:44:26
    .io_currentStatus_cond_n            (cpsr_cond_n),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_cond_z            (cpsr_cond_z),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_cond_c            (cpsr_cond_c),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_cond_v            (cpsr_cond_v),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_irqDisable        (cpsr_irqDisable),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_fiqDisable        (cpsr_fiqDisable),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_thumb             (cpsr_thumb),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_currentStatus_mode              (cpsr_mode),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_nextStatus_thumb                (enable ? _GEN_11 : cpsr_thumb),	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :89:21, :113:29, :138:17, :173:47, :176:35, :179:22
    .io_multiplierDone                  (_multiplier_io_done),	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
    .io_fiq                             (io_FIQ),
    .io_irq                             (io_IRQ)
  );
  Shifter shifter (	// src/main/scala/gba/cpu/ARM7TDMI.scala:198:23
    .clock              (clock),
    .io_in              (bBus),	// src/main/scala/gba/cpu/ARM7TDMI.scala:232:48, :274:49, :276:10
    .io_shiftKind       (_controlUnit_io_signals_shiftKind),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_shiftAmount
      (_controlUnit_io_signals_shiftByAddressAlign
         ? {1'h0, lastMemReadAlign, 3'h0}
         : _controlUnit_io_signals_shiftImmediate),	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27, :121:22, :202:26, :249:29, :302:38, :303:28
    .io_out             (_shifter_io_out),
    .io_carryIn         (cpsr_cond_c),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_carryOut        (_shifter_io_carryOut),
    .io_latchShift      (enable & _controlUnit_io_signals_shiftDoLatch),	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26, :53:27, :203:35
    .io_useLatchedShift (_controlUnit_io_signals_shiftUseLatched)	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
  );
  Alu alu (	// src/main/scala/gba/cpu/ARM7TDMI.scala:207:19
    .io_opcode       (_controlUnit_io_signals_aluOpcode),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_a
      (({32{~_controlUnit_io_signals_aluInAAlign4}} | 32'hFFFFFFFC) & aBus),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27, :120:8, :208:12, :209:31, :210:{14,22}
    .io_b            (_shifter_io_out),	// src/main/scala/gba/cpu/ARM7TDMI.scala:198:23
    .io_flagIn_c     (cpsr_cond_c),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_flagIn_v     (cpsr_cond_v),	// src/main/scala/gba/cpu/ARM7TDMI.scala:89:21
    .io_shifterCarry (_shifter_io_carryOut),	// src/main/scala/gba/cpu/ARM7TDMI.scala:198:23
    .io_out          (_alu_io_out),
    .io_flagOut_n    (_alu_io_flagOut_n),
    .io_flagOut_z    (_alu_io_flagOut_z),
    .io_flagOut_c    (_alu_io_flagOut_c),
    .io_flagOut_v    (_alu_io_flagOut_v)
  );
  Multiplier multiplier (	// src/main/scala/gba/cpu/ARM7TDMI.scala:223:26
    .clock              (clock),
    .io_enable          (enable),	// src/main/scala/gba/cpu/ARM7TDMI.scala:26:26
    .io_a               (aBus),	// src/main/scala/gba/cpu/ARM7TDMI.scala:120:8
    .io_b               (bBus),	// src/main/scala/gba/cpu/ARM7TDMI.scala:232:48, :274:49, :276:10
    .io_start           (_controlUnit_io_signals_multiplyEnable),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_loadAccumulator (_controlUnit_io_signals_multiplyLoadAccumulator),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_accumulate      (_controlUnit_io_signals_multiplyAccumulate),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_signed          (_controlUnit_io_signals_multiplySigned),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_long            (_controlUnit_io_signals_multiplyLong),	// src/main/scala/gba/cpu/ARM7TDMI.scala:53:27
    .io_outLo           (_multiplier_io_outLo),
    .io_outHi           (_multiplier_io_outHi),
    .io_done            (_multiplier_io_done),
    .io_outFlagZ        (_multiplier_io_outFlagZ),
    .io_outFlagN        (_multiplier_io_outFlagN)
  );
  assign io_debug_registers_0 = registers[5'h0];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_1 = registers[5'h1];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_2 = registers[5'h2];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_3 = registers[5'h3];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_4 = registers[5'h4];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_5 = registers[5'h5];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_6 = registers[5'h6];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_7 = registers[5'h7];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_registers_8 = _GEN[_GEN_17 + 5'h8];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_9 = _GEN[_GEN_17 + 5'h9];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_10 = _GEN[_GEN_17 + 5'hA];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_11 = _GEN[_GEN_17 + 5'hB];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_12 = _GEN[_GEN_17 + 5'hC];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_13 = _GEN[offset_15 + 5'hD];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :73:66, :74:14, :75:52, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_14 = _GEN[offset_15 + 5'hE];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :73:66, :74:14, :75:52, :86:11, :120:8, :138:17, :315:32
  assign io_debug_registers_15 = registers[5'hF];	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :70:26, :138:17
  assign io_debug_cpsr =
    {cpsr_cond_n,
     cpsr_cond_z,
     cpsr_cond_c,
     cpsr_cond_v,
     cpsr_padding,
     cpsr_irqDisable,
     cpsr_fiqDisable,
     cpsr_thumb,
     cpsr_mode};	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :89:21, :318:25
  assign io_mem_SIZE = _controlUnit_io_signals_memWidth;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27
  assign io_mem_PROT_privileged = 1'h0;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :53:27
  assign io_mem_ADDR =
    _GEN_12
      ? _incrementerBus_T_3
      : _GEN_13
          ? registers[5'hF]
          : _GEN_14 ? aluBus : _GEN_15 ? _controlUnit_io_signals_immediate : memAddrReg;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :29:23, :53:27, :70:26, :138:17, :216:10, :217:31, :218:12, :244:32, :250:15, :251:34, :252:50, :253:41, :254:42, :255:48
  assign io_mem_WDATA =
    currentMemReadWidth == 2'h0
      ? {2{{2{cBus[7:0]}}}}
      : currentMemReadWidth == 2'h1 ? {2{cBus[15:0]}} : cBus;	// src/main/scala/gba/cpu/ARM7TDMI.scala:10:7, :86:11, :133:8, :247:32, :267:{29,54}, :268:{18,25,33}, :269:{36,65}, :270:{18,25,33}, :272:18
endmodule

