// Generated by CIRCT firtool-1.62.0
module Control(	// src/main/scala/gba/cpu/Control.scala:98:7
  input         clock,	// src/main/scala/gba/cpu/Control.scala:98:7
                reset,	// src/main/scala/gba/cpu/Control.scala:98:7
                io_enable,	// src/main/scala/gba/cpu/Control.scala:99:14
  output        io_signals_advancePipeline,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_flushPipeline,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_startException,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_pcNext,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [2:0]  io_signals_addressSource,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [4:0]  io_signals_regBankMode,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [3:0]  io_signals_regReadA,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_regReadB,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_regReadC,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_regWriteIndex,	// src/main/scala/gba/cpu/Control.scala:99:14
  output        io_signals_regWriteEnable,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_regUserReadC,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_regUserWrite,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_cpsrUpdateCond,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_cpsrUpdateThumb,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [1:0]  io_signals_cpsrUpdateFields,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_spsrUpdateFields,	// src/main/scala/gba/cpu/Control.scala:99:14
  output        io_signals_cpsrRestore,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_cpsrFromMultiply,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [2:0]  io_signals_busB,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [31:0] io_signals_immediate,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [3:0]  io_signals_aluOpcode,	// src/main/scala/gba/cpu/Control.scala:99:14
  output        io_signals_aluOutAlign4,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_aluInAAlign4,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [2:0]  io_signals_shiftKind,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [5:0]  io_signals_shiftImmediate,	// src/main/scala/gba/cpu/Control.scala:99:14
  output        io_signals_shiftDoLatch,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_shiftUseLatched,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_shiftByAddressAlign,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_multiplyEnable,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_multiplySigned,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_multiplyLoadAccumulator,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_multiplyAccumulate,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_multiplyLong,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_memRequest,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_memSequential,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_memWrite,	// src/main/scala/gba/cpu/Control.scala:99:14
  output [1:0]  io_signals_memWidth,	// src/main/scala/gba/cpu/Control.scala:99:14
  output        io_signals_memProt_data,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_memLock,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_latchMemReadData,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_memReadDataSigned,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_signals_incrementerForceWord,	// src/main/scala/gba/cpu/Control.scala:99:14
  input  [3:0]  io_nextInstruction_kind,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_nextInstruction_condition,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_nextInstruction_regN,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_nextInstruction_regD,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_nextInstruction_regS,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_nextInstruction_regM,	// src/main/scala/gba/cpu/Control.scala:99:14
  input  [23:0] io_nextInstruction_immediate,	// src/main/scala/gba/cpu/Control.scala:99:14
  input  [3:0]  io_nextInstruction_opcode,	// src/main/scala/gba/cpu/Control.scala:99:14
  input  [6:0]  io_nextInstruction_flags,	// src/main/scala/gba/cpu/Control.scala:99:14
  input         io_currentStatus_cond_n,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_currentStatus_cond_z,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_currentStatus_cond_c,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_currentStatus_cond_v,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_currentStatus_irqDisable,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_currentStatus_fiqDisable,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_currentStatus_thumb,	// src/main/scala/gba/cpu/Control.scala:99:14
  input  [4:0]  io_currentStatus_mode,	// src/main/scala/gba/cpu/Control.scala:99:14
  input         io_nextStatus_thumb,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_multiplierDone,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_fiq,	// src/main/scala/gba/cpu/Control.scala:99:14
                io_irq	// src/main/scala/gba/cpu/Control.scala:99:14
);

  wire [3:0]       io_signals_regWriteIndex_0;	// src/main/scala/gba/cpu/Control.scala:217:31, :240:24
  wire             io_signals_cpsrUpdateCond_0;	// src/main/scala/gba/cpu/Control.scala:180:26, :216:18, :217:31
  reg  [3:0]       instruction_kind;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [3:0]       instruction_condition;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [3:0]       instruction_regN;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [3:0]       instruction_regD;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [3:0]       instruction_regS;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [3:0]       instruction_regM;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [23:0]      instruction_immediate;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [3:0]       instruction_opcode;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [6:0]       instruction_flags;	// src/main/scala/gba/cpu/Control.scala:122:28
  reg  [2:0]       stage;	// src/main/scala/gba/cpu/Control.scala:127:22
  reg  [4:0]       counter;	// src/main/scala/gba/cpu/Control.scala:129:20
  wire             _execute_T_15 = io_currentStatus_cond_n ^ io_currentStatus_cond_v;	// src/main/scala/gba/cpu/Control.scala:993:33
  wire             _execute_T_35 =
    instruction_condition == 4'h0 & io_currentStatus_cond_z;	// <stdin>:1641:5, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire [15:0]      _GEN =
    {{_execute_T_35},
     {_execute_T_35},
     {io_currentStatus_cond_z | _execute_T_15},
     {~io_currentStatus_cond_z & ~_execute_T_15},
     {_execute_T_15},
     {~_execute_T_15},
     {~io_currentStatus_cond_c | io_currentStatus_cond_z},
     {io_currentStatus_cond_c & ~io_currentStatus_cond_z},
     {~io_currentStatus_cond_v},
     {io_currentStatus_cond_v},
     {~io_currentStatus_cond_n},
     {io_currentStatus_cond_n},
     {~io_currentStatus_cond_c},
     {io_currentStatus_cond_c},
     {~io_currentStatus_cond_z},
     {_execute_T_35}};	// src/main/scala/gba/cpu/Control.scala:982:34, :984:23, :986:23, :988:23, :990:23, :991:32, :992:33, :993:{23,33}, :995:{33,36}, :996:32
  wire             execute =
    instruction_condition != 4'hF
    & (instruction_condition == 4'hE | _GEN[instruction_condition]);	// <stdin>:1645:42, src/main/scala/gba/cpu/Control.scala:122:28, :137:42, :982:34
  wire             _GEN_0 = instruction_kind == 4'h0;	// <stdin>:1641:5, :1893:20, src/main/scala/gba/cpu/Control.scala:122:28
  wire             _GEN_1 = instruction_kind == 4'h1;	// <stdin>:1639:39, :1917:20, src/main/scala/gba/cpu/Control.scala:122:28
  wire             _GEN_2 = instruction_kind == 4'h2;	// <stdin>:1941:20, src/main/scala/gba/cpu/Control.scala:122:28, :273:31
  wire             _GEN_3 = instruction_kind == 4'h3;	// <stdin>:1965:20, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/gba/cpu/Control.scala:122:28
  wire             _GEN_4 = instruction_kind == 4'h4;	// <stdin>:1989:20, src/main/scala/gba/cpu/Control.scala:122:28, :540:33
  wire             _GEN_5 = instruction_kind == 4'h5;	// <stdin>:2013:20, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/gba/cpu/Control.scala:122:28
  wire             _GEN_6 = instruction_kind == 4'h6;	// <stdin>:2037:20, src/main/scala/gba/cpu/Control.scala:122:28, :150:28
  wire             _GEN_7 = instruction_kind == 4'h7;	// <stdin>:2061:20, src/main/scala/gba/cpu/Control.scala:122:28, :146:28
  wire             _GEN_8 = instruction_kind == 4'h8;	// <stdin>:2085:20, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire             _GEN_9 = instruction_kind == 4'h9;	// <stdin>:2109:20, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire             _GEN_10 = instruction_kind == 4'hA;	// <stdin>:2133:20, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire             _GEN_11 = instruction_kind == 4'hB;	// <stdin>:2157:20, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire             _GEN_12 = instruction_kind == 4'hC;	// <stdin>:2181:20, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire             _GEN_13 = instruction_kind == 4'hD;	// <stdin>:2205:20, src/main/scala/gba/cpu/Control.scala:122:28, :982:34
  wire [4:0]       _newMode_T_11 = {1'h1, instruction_opcode[2:0] == 3'h2, 3'h3};	// src/main/scala/gba/cpu/Control.scala:122:28, :219:64, :229:58, :276:39, :297:29, :982:34
  wire [7:0][4:0]  _GEN_14 =
    {{5'h11},
     {5'h12},
     {5'h17},
     {5'h17},
     {5'h13},
     {_newMode_T_11},
     {_newMode_T_11},
     {_newMode_T_11}};	// src/main/scala/gba/cpu/Control.scala:229:58
  reg              entryThumb;	// src/main/scala/gba/cpu/Control.scala:238:29
  wire             _GEN_15 = stage == 3'h0;	// src/main/scala/gba/cpu/Control.scala:127:22, :240:24
  wire             _GEN_16 = stage == 3'h1;	// src/main/scala/gba/cpu/Control.scala:127:22, :240:24, :280:26
  wire             _GEN_17 = _GEN_15 | _GEN_16;	// src/main/scala/gba/cpu/Control.scala:240:24, :264:36
  wire             _GEN_18 = stage == 3'h2;	// src/main/scala/gba/cpu/Control.scala:127:22, :240:24, :276:39
  wire             _GEN_19 = ~_GEN_15 & (_GEN_16 | _GEN_18);	// src/main/scala/gba/cpu/Control.scala:240:24, :261:26, :952:20, :964:20
  wire             _GEN_20 = _GEN_16 | _GEN_18;	// src/main/scala/gba/cpu/Control.scala:171:25, :240:24, :953:27
  wire [2:0]       _GEN_21 = {2'h0, _GEN_20};	// src/main/scala/gba/cpu/Control.scala:171:25, :240:24, :528:41, :953:27
  wire [1:0]       _GEN_22 = io_nextStatus_thumb ? 2'h1 : 2'h2;	// src/main/scala/gba/cpu/Control.scala:240:24, :969:{22,28}, :982:34
  wire             _GEN_23 = _GEN_15 | _GEN_16;	// src/main/scala/gba/cpu/Control.scala:240:24, :956:24, :970:24
  wire             _GEN_24 = _GEN_23 | _GEN_18;	// src/main/scala/gba/cpu/Control.scala:240:24, :956:24, :970:24
  wire             _GEN_25 = ~_GEN_23 & _GEN_18;	// src/main/scala/gba/cpu/Control.scala:240:24, :247:22, :285:22, :956:24, :970:24
  wire             _io_signals_regWriteEnable_T = instruction_opcode[3:2] != 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :907:{38,45}, :982:34
  wire             _GEN_26 = (&instruction_regD) & io_signals_cpsrUpdateCond_0;	// src/main/scala/gba/cpu/Control.scala:122:28, :180:26, :216:18, :217:31, :916:{28,37}
  wire             _GEN_27 = (&instruction_regD) & _io_signals_regWriteEnable_T;	// src/main/scala/gba/cpu/Control.scala:122:28, :907:45, :916:28, :921:37
  wire             _GEN_28 = instruction_immediate[6:2] == 5'h0;	// src/main/scala/gba/cpu/Control.scala:122:28, :309:51, :315:30
  wire             _GEN_29 =
    instruction_immediate[1:0] == 2'h1 | instruction_immediate[1:0] == 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :310:72, :316:29, :969:28, :982:34
  wire             _io_signals_regWriteEnable_T_1 = instruction_opcode[3:2] != 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :907:{38,45}, :982:34
  wire             _GEN_30 = (&instruction_regD) & _io_signals_regWriteEnable_T_1;	// src/main/scala/gba/cpu/Control.scala:122:28, :907:45, :916:28, :921:37
  wire             _GEN_31 = _GEN_0 | _GEN_1 | _GEN_2;	// <stdin>:1893:20, :1917:20, :1941:20, src/main/scala/gba/cpu/Control.scala:193:24, :217:31
  wire             _GEN_32 = ~_GEN_15 & _GEN_16;	// src/main/scala/gba/cpu/Control.scala:194:27, :240:24, :261:26, :330:24
  wire             _io_signals_regWriteEnable_T_2 = instruction_opcode[3:2] != 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :907:{38,45}, :982:34
  assign io_signals_cpsrUpdateCond_0 =
    execute & ~_GEN_0
    & (_GEN_1
         ? instruction_flags[0]
         : _GEN_2
             ? instruction_flags[0]
             : _GEN_3 & ~_GEN_15 & _GEN_16 & instruction_flags[0]);	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, src/main/scala/gba/cpu/Control.scala:122:28, :180:26, :216:18, :217:31, :240:24, :261:26, :330:24, :913:{28,48}, :982:34
  wire             _GEN_33 = (&instruction_regD) & _io_signals_regWriteEnable_T_2;	// src/main/scala/gba/cpu/Control.scala:122:28, :907:45, :916:28, :921:37
  wire             _GEN_34 = instruction_immediate[6:2] == 5'h0;	// src/main/scala/gba/cpu/Control.scala:122:28, :315:30, :883:49, :887:28
  wire             _GEN_35 =
    instruction_immediate[1:0] == 2'h1 | instruction_immediate[1:0] == 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :884:70, :888:28, :969:28, :982:34
  wire             _GEN_36 = ~(instruction_flags[2]) | instruction_flags[3];	// src/main/scala/gba/cpu/Control.scala:122:28, :192:26, :352:47, :353:46, :360:34, :877:27
  wire             _GEN_37 = instruction_immediate[6:2] == 5'h0;	// src/main/scala/gba/cpu/Control.scala:122:28, :315:30, :883:49, :887:28
  wire             _GEN_38 =
    instruction_immediate[1:0] == 2'h1 | instruction_immediate[1:0] == 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :884:70, :888:28, :969:28, :982:34
  wire             _GEN_39 = _GEN_16 & instruction_flags[0];	// src/main/scala/gba/cpu/Control.scala:122:28, :192:26, :240:24, :355:47, :357:24, :379:35, :877:27
  wire             _GEN_40 = _GEN_31 | _GEN_3;	// <stdin>:1965:20, src/main/scala/gba/cpu/Control.scala:193:24, :210:29, :217:31
  wire             _GEN_41 = instruction_immediate[6:2] == 5'h0;	// src/main/scala/gba/cpu/Control.scala:122:28, :315:30, :883:49, :887:28
  wire             _GEN_42 =
    instruction_immediate[1:0] == 2'h1 | instruction_immediate[1:0] == 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :884:70, :888:28, :969:28, :982:34
  wire             _GEN_43 = ~(instruction_flags[2]) | instruction_flags[3];	// src/main/scala/gba/cpu/Control.scala:122:28, :192:26, :411:47, :412:46, :420:34, :877:27
  wire             _GEN_44 = ~_GEN_15 | instruction_flags[2];	// src/main/scala/gba/cpu/Control.scala:122:28, :240:24, :261:26, :412:46, :416:24, :420:34
  wire             _GEN_45 = instruction_immediate[6:2] == 5'h0;	// src/main/scala/gba/cpu/Control.scala:122:28, :315:30, :883:49, :887:28
  wire             _GEN_46 =
    instruction_immediate[1:0] == 2'h1 | instruction_immediate[1:0] == 2'h2;	// src/main/scala/gba/cpu/Control.scala:122:28, :884:70, :888:28, :969:28, :982:34
  wire             _GEN_47 = _GEN_16 & instruction_flags[0];	// src/main/scala/gba/cpu/Control.scala:122:28, :192:26, :240:24, :414:47, :416:24, :440:35, :877:27
  wire             _GEN_48 = ~_GEN_47 | instruction_flags[3];	// src/main/scala/gba/cpu/Control.scala:122:28, :192:26, :411:47, :416:24, :440:35, :877:27
  wire             _GEN_49 = _GEN_40 | _GEN_4;	// <stdin>:1989:20, src/main/scala/gba/cpu/Control.scala:207:19, :210:29, :217:31
  wire             _GEN_50 = _GEN_49 | _GEN_5;	// <stdin>:2013:20, src/main/scala/gba/cpu/Control.scala:207:19, :217:31
  wire             _GEN_51 = stage == 3'h3;	// src/main/scala/gba/cpu/Control.scala:127:22, :297:29, :460:24
  wire             _GEN_52 = ~(_GEN_23 | _GEN_18) & _GEN_51;	// src/main/scala/gba/cpu/Control.scala:195:31, :240:24, :460:24, :956:24, :970:24
  wire             _GEN_53 = _GEN_50 | _GEN_6;	// <stdin>:2037:20, src/main/scala/gba/cpu/Control.scala:181:27, :207:19, :217:31
  wire [2:0]       _GEN_54 = _GEN_15 ? 3'h3 : _GEN_21;	// src/main/scala/gba/cpu/Control.scala:171:25, :240:24, :297:29, :516:24, :953:27, :965:27
  wire             _GEN_55 = _GEN_7 | _GEN_13 | _GEN_8;	// <stdin>:2061:20, :2085:20, :2205:20, src/main/scala/gba/cpu/Control.scala:183:28, :217:31
  wire             _GEN_56 =
    _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_55;	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, src/main/scala/gba/cpu/Control.scala:183:28, :217:31
  wire [4:0]       regCount =
    {1'h0,
     {1'h0,
      {1'h0, {1'h0, instruction_immediate[0]} + {1'h0, instruction_immediate[1]}}
        + {1'h0, {1'h0, instruction_immediate[2]} + {1'h0, instruction_immediate[3]}}}
       + {1'h0,
          {1'h0, {1'h0, instruction_immediate[4]} + {1'h0, instruction_immediate[5]}}
            + {1'h0,
               {1'h0, instruction_immediate[6]} + {1'h0, instruction_immediate[7]}}}}
    + {1'h0,
       {1'h0,
        {1'h0, {1'h0, instruction_immediate[8]} + {1'h0, instruction_immediate[9]}}
          + {1'h0, {1'h0, instruction_immediate[10]} + {1'h0, instruction_immediate[11]}}}
         + {1'h0,
            {1'h0, {1'h0, instruction_immediate[12]} + {1'h0, instruction_immediate[13]}}
              + {1'h0,
                 {1'h0, instruction_immediate[14]} + {1'h0, instruction_immediate[15]}}}};	// <stdin>:1635:5, src/main/scala/gba/cpu/Control.scala:122:28, :636:44, :638:32
  wire [3:0]       regNextIndex =
    (|(instruction_immediate[15:0]))
      ? (instruction_immediate[0]
           ? 4'h0
           : instruction_immediate[1]
               ? 4'h1
               : instruction_immediate[2]
                   ? 4'h2
                   : instruction_immediate[3]
                       ? 4'h3
                       : instruction_immediate[4]
                           ? 4'h4
                           : instruction_immediate[5]
                               ? 4'h5
                               : instruction_immediate[6]
                                   ? 4'h6
                                   : instruction_immediate[7]
                                       ? 4'h7
                                       : instruction_immediate[8]
                                           ? 4'h8
                                           : instruction_immediate[9]
                                               ? 4'h9
                                               : instruction_immediate[10]
                                                   ? 4'hA
                                                   : instruction_immediate[11]
                                                       ? 4'hB
                                                       : instruction_immediate[12]
                                                           ? 4'hC
                                                           : instruction_immediate[13]
                                                               ? 4'hD
                                                               : {3'h7,
                                                                  ~(instruction_immediate[14])})
      : 4'hF;	// <stdin>:1639:39, :1641:5, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/gba/cpu/Control.scala:122:28, :137:42, :146:{28,49}, :150:28, :273:31, :540:33, :636:44, :637:36, :638:32, :639:31, :982:34
  wire             _GEN_57 = _GEN_16 | _GEN_15;	// src/main/scala/gba/cpu/Control.scala:192:26, :240:24, :641:30, :653:34, :665:30, :674:34
  wire             _GEN_58 = _GEN_7 | _GEN_13 | _GEN_8 | _GEN_9;	// <stdin>:2061:20, :2085:20, :2109:20, :2205:20, src/main/scala/gba/cpu/Control.scala:208:28, :217:31
  wire             _GEN_59 = ~(|counter) & io_nextStatus_thumb;	// src/main/scala/gba/cpu/Control.scala:129:20, :687:28, :691:{25,34}, :936:{22,28}
  wire [2:0]       _GEN_60 = (|counter) ? 3'h1 : 3'h2;	// src/main/scala/gba/cpu/Control.scala:129:20, :276:39, :280:26, :682:33, :691:{25,34}, :694:35
  wire             _GEN_61 = _GEN_20 & ~(|counter);	// src/main/scala/gba/cpu/Control.scala:129:20, :171:25, :240:24, :641:30, :680:47, :691:{25,34}, :695:28, :953:27
  wire             _GEN_62 = _GEN_53 | _GEN_7 | _GEN_13 | _GEN_8 | _GEN_9;	// <stdin>:2061:20, :2085:20, :2109:20, :2205:20, src/main/scala/gba/cpu/Control.scala:179:24, :181:27, :217:31
  wire             _GEN_63 = _GEN_10 & _GEN_51;	// <stdin>:2133:20, src/main/scala/gba/cpu/Control.scala:168:25, :217:31, :460:24, :715:30, :717:49
  wire             _GEN_64 = _GEN_8 | _GEN_9;	// <stdin>:2085:20, :2109:20, src/main/scala/gba/cpu/Control.scala:168:25, :217:31
  wire             _GEN_65 = _GEN_7 | _GEN_13;	// <stdin>:2061:20, :2205:20, src/main/scala/gba/cpu/Control.scala:217:31, :516:24
  wire             regListEmpty_1 = instruction_immediate[15:0] == 16'h0;	// src/main/scala/gba/cpu/Control.scala:122:28, :637:36, :733:44, :734:36
  wire [4:0]       regCount_1 =
    {1'h0,
     {1'h0,
      {1'h0, {1'h0, instruction_immediate[0]} + {1'h0, instruction_immediate[1]}}
        + {1'h0, {1'h0, instruction_immediate[2]} + {1'h0, instruction_immediate[3]}}}
       + {1'h0,
          {1'h0, {1'h0, instruction_immediate[4]} + {1'h0, instruction_immediate[5]}}
            + {1'h0,
               {1'h0, instruction_immediate[6]} + {1'h0, instruction_immediate[7]}}}}
    + {1'h0,
       {1'h0,
        {1'h0, {1'h0, instruction_immediate[8]} + {1'h0, instruction_immediate[9]}}
          + {1'h0, {1'h0, instruction_immediate[10]} + {1'h0, instruction_immediate[11]}}}
         + {1'h0,
            {1'h0, {1'h0, instruction_immediate[12]} + {1'h0, instruction_immediate[13]}}
              + {1'h0,
                 {1'h0, instruction_immediate[14]} + {1'h0, instruction_immediate[15]}}}};	// <stdin>:1635:5, src/main/scala/gba/cpu/Control.scala:122:28, :733:44, :735:32
  wire [3:0]       regNextIndex_1 =
    regListEmpty_1
      ? 4'hF
      : instruction_immediate[0]
          ? 4'h0
          : instruction_immediate[1]
              ? 4'h1
              : instruction_immediate[2]
                  ? 4'h2
                  : instruction_immediate[3]
                      ? 4'h3
                      : instruction_immediate[4]
                          ? 4'h4
                          : instruction_immediate[5]
                              ? 4'h5
                              : instruction_immediate[6]
                                  ? 4'h6
                                  : instruction_immediate[7]
                                      ? 4'h7
                                      : instruction_immediate[8]
                                          ? 4'h8
                                          : instruction_immediate[9]
                                              ? 4'h9
                                              : instruction_immediate[10]
                                                  ? 4'hA
                                                  : instruction_immediate[11]
                                                      ? 4'hB
                                                      : instruction_immediate[12]
                                                          ? 4'hC
                                                          : instruction_immediate[13]
                                                              ? 4'hD
                                                              : {3'h7,
                                                                 ~(instruction_immediate[14])};	// <stdin>:1639:39, :1641:5, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/gba/cpu/Control.scala:122:28, :137:42, :146:{28,49}, :150:28, :273:31, :540:33, :733:44, :734:36, :735:32, :736:31, :982:34
  wire             _GEN_66 = _GEN_4 | _GEN_5;	// <stdin>:1989:20, :2013:20, src/main/scala/gba/cpu/Control.scala:217:31, :357:24
  wire [5:0]       _GEN_67 = {4'h0, (_GEN_10 | _GEN_11) & _GEN_57, 1'h0};	// <stdin>:1635:5, :1641:5, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:192:26, :217:31, :641:30, :653:34, :665:30, :674:34
  wire [15:0][5:0] _GEN_68 =
    {{_GEN_67},
     {_GEN_67},
     {6'h0},
     {_GEN_67},
     {_GEN_67},
     {_GEN_67},
     {instruction_flags[1] ? {1'h0, instruction_immediate[11:8], 1'h0} : 6'h0},
     {6'h0},
     {6'h0},
     {6'h0},
     {_GEN_15
        ? (_GEN_43
             ? 6'h0
             : _GEN_41 & _GEN_42 ? 6'h20 : {1'h0, instruction_immediate[6:2]})
        : _GEN_48
            ? 6'h0
            : _GEN_45 & _GEN_46 ? 6'h20 : {1'h0, instruction_immediate[6:2]}},
     {_GEN_15
        ? (_GEN_36
             ? 6'h0
             : _GEN_34 & _GEN_35 ? 6'h20 : {1'h0, instruction_immediate[6:2]})
        : ~_GEN_39 | instruction_flags[3]
            ? 6'h0
            : _GEN_37 & _GEN_38 ? 6'h20 : {1'h0, instruction_immediate[6:2]}},
     {6'h0},
     {_GEN_28 & _GEN_29 ? 6'h20 : {1'h0, instruction_immediate[6:2]}},
     {instruction_flags[1] ? 6'h0 : {1'h0, instruction_immediate[11:8], 1'h0}},
     {6'h0}};	// <stdin>:1635:5, :1893:20, :1895:53, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2109:20, src/main/scala/gba/cpu/Control.scala:122:28, :183:28, :192:26, :217:31, :240:24, :296:{32,45}, :298:{34,58}, :309:51, :314:32, :315:{30,39}, :316:29, :319:38, :352:47, :357:24, :360:34, :379:35, :416:24, :420:34, :440:35, :529:23, :611:47, :612:31, :614:{34,58}, :665:30, :877:27, :883:49, :886:30, :887:{28,37}, :888:28, :891:36
  wire             _GEN_69 = _GEN_11 & (|stage);	// <stdin>:2157:20, src/main/scala/gba/cpu/Control.scala:127:22, :178:24, :217:31, :773:{21,29}, :783:32
  wire             _GEN_70 = _GEN_62 | _GEN_10;	// <stdin>:2133:20, src/main/scala/gba/cpu/Control.scala:178:24, :179:24, :217:31
  wire             _GEN_71 =
    _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_13
    | _GEN_64;	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2061:20, :2205:20, src/main/scala/gba/cpu/Control.scala:130:32, :168:25, :217:31
  wire             _GEN_72 = _GEN_15 & instruction_flags[1];	// src/main/scala/gba/cpu/Control.scala:122:28, :240:24, :805:48, :815:29
  wire             _GEN_73 = _GEN_70 | _GEN_11;	// <stdin>:2157:20, src/main/scala/gba/cpu/Control.scala:178:24, :198:35, :217:31
  wire             _GEN_74 = _GEN_15 & ~(instruction_flags[1]) | _GEN_16;	// src/main/scala/gba/cpu/Control.scala:122:28, :240:24, :805:48, :826:{30,33,51}
  wire [3:0]       _GEN_75 = _GEN_74 ? instruction_regM : instruction_regD;	// src/main/scala/gba/cpu/Control.scala:122:28, :815:49, :826:{51,69}, :828:28
  wire [15:0][3:0] _GEN_76 =
    {{_GEN_75},
     {_GEN_75},
     {{3'h7, ~_GEN_15}},
     {_GEN_75},
     {instruction_regN},
     {instruction_regN},
     {_GEN_75},
     {_GEN_75},
     {_GEN_15 & instruction_flags[1] ? instruction_regM : 4'hF},
     {_GEN_75},
     {instruction_regN},
     {instruction_regN},
     {instruction_regN},
     {instruction_regN},
     {instruction_regN},
     {4'hE}};	// <stdin>:1645:42, :1893:20, :2061:20, :2205:20, src/main/scala/gba/cpu/Control.scala:122:28, :137:42, :146:49, :217:31, :240:24, :261:26, :330:24, :357:24, :416:24, :513:46, :516:24, :518:34, :519:32, :525:32, :568:24, :570:30, :665:30, :760:30, :815:49, :826:69, :828:28, :909:22
  wire             _GEN_77 = _GEN_12 & _GEN_74;	// <stdin>:2181:20, src/main/scala/gba/cpu/Control.scala:196:26, :217:31, :826:{51,69}
  wire [2:0]       _GEN_78 = {2'h0, _GEN_12 & _GEN_74};	// <stdin>:2181:20, src/main/scala/gba/cpu/Control.scala:171:25, :217:31, :528:41, :815:49, :826:{51,69}, :934:27
  wire [15:0][2:0] _GEN_79 =
    {{_GEN_78},
     {_GEN_78},
     {_GEN_54},
     {_GEN_78},
     {(|stage) ? _GEN_60 : _GEN_15 ? 3'h3 : 3'h0},
     {_GEN_51 & (&io_signals_regWriteIndex_0)
        ? 3'h3
        : _GEN_20 ? _GEN_60 : _GEN_57 ? 3'h3 : 3'h0},
     {3'h1},
     {3'h1},
     {_GEN_54},
     {_GEN_15 ? 3'h3 : _GEN_16 ? 3'h0 : {1'h0, _GEN_18, 1'h0}},
     {_GEN_15 ? 3'h3 : {1'h0, _GEN_16, 1'h0}},
     {_GEN_15 ? 3'h3 : _GEN_16 ? 3'h2 : _GEN_18 & (&instruction_regD) ? 3'h3 : 3'h0},
     {_GEN_15 ? 3'h1 : _GEN_16 & _GEN_33 ? 3'h3 : 3'h0},
     {{1'h0, _GEN_30, 1'h1}},
     {{1'h0, _GEN_27, 1'h1}},
     {_GEN_15 ? 3'h4 : _GEN_21}};	// <stdin>:1635:5, :1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:122:28, :127:22, :168:25, :171:25, :192:26, :217:31, :240:24, :251:35, :276:39, :280:26, :297:29, :330:24, :357:24, :367:35, :387:35, :400:46, :416:24, :427:35, :453:35, :460:24, :466:35, :482:35, :494:35, :516:24, :641:30, :653:34, :654:33, :665:30, :674:34, :675:33, :680:47, :682:33, :691:34, :694:35, :715:30, :717:{39,49}, :738:30, :749:33, :773:{21,29}, :786:34, :815:49, :826:69, :916:28, :921:{37,51}, :934:27, :953:27, :965:27, :982:34
  wire             _GEN_80 = _GEN_18 & io_multiplierDone;	// src/main/scala/gba/cpu/Control.scala:240:24, :836:29
  wire             _GEN_81 = _GEN_1 | _GEN_2;	// <stdin>:1917:20, :1941:20, src/main/scala/gba/cpu/Control.scala:128:30, :217:31
  wire [15:0][3:0] _GEN_82 =
    {{4'hD},
     {4'hD},
     {_GEN_15 ? 4'h4 : 4'h2},
     {4'hD},
     {{1'h0, instruction_flags[2] ? 3'h4 : 3'h2}},
     {(|(stage[2:1])) ? 4'hD : {1'h0, instruction_flags[2] ? 3'h4 : 3'h2}},
     {4'hD},
     {4'hD},
     {_GEN_15 ? (instruction_flags[1] ? 4'hE : 4'h4) : 4'h2},
     {4'hD},
     {_GEN_15
        ? (instruction_flags[2] ? {1'h0, instruction_flags[1] ? 3'h4 : 3'h2} : 4'hD)
        : {1'h0, instruction_flags[1] ? 3'h4 : 3'h2}},
     {_GEN_15
        ? (instruction_flags[2] ? {1'h0, instruction_flags[1] ? 3'h4 : 3'h2} : 4'hD)
        : _GEN_16 ? {1'h0, instruction_flags[1] ? 3'h4 : 3'h2} : 4'hD},
     {instruction_opcode},
     {instruction_opcode},
     {instruction_opcode},
     {_GEN_15 ? 4'hD : 4'h2}};	// <stdin>:1635:5, :1645:42, :1893:20, :1989:20, :2013:20, :2037:20, :2061:20, :2133:20, :2157:20, :2205:20, src/main/scala/gba/cpu/Control.scala:122:28, :127:22, :168:25, :217:31, :240:24, :262:31, :273:31, :276:39, :353:46, :354:41, :357:24, :360:34, :365:33, :379:35, :412:46, :413:41, :416:24, :420:34, :425:33, :460:24, :513:46, :516:24, :518:34, :522:33, :540:33, :568:24, :573:31, :603:27, :621:27, :632:40, :641:30, :665:30, :672:29, :706:{21,29}, :709:29, :729:40, :738:30, :760:30, :767:29, :902:{23,29}, :910:23, :982:34
  wire [2:0]       _GEN_83 = _GEN_51 ? 3'h6 : _GEN_80 ? 3'h5 : 3'h0;	// src/main/scala/gba/cpu/Control.scala:127:22, :150:49, :460:24, :826:69, :836:{29,51}, :840:24, :855:30, :859:24, :982:34
  wire [15:0][2:0] _GEN_84 =
    {{_GEN_83},
     {_GEN_83},
     {3'h1},
     {_GEN_83},
     {3'h1},
     {(|(stage[2:1])) ? 3'h2 : 3'h1},
     {{2'h0, instruction_flags[1]}},
     {instruction_flags[0] ? 3'h4 : 3'h3},
     {3'h1},
     {{1'h0, ~_GEN_15, 1'h0}},
     {{2'h0, _GEN_44 & instruction_flags[3]}},
     {_GEN_15
        ? {2'h0, instruction_flags[2] & instruction_flags[3]}
        : _GEN_16 ? {2'h0, instruction_flags[3]} : 3'h2},
     {3'h0},
     {3'h0},
     {3'h1},
     {{2'h0, ~_GEN_15}}};	// <stdin>:1635:5, :1893:20, :1917:20, :1989:20, :2013:20, :2037:20, :2085:20, :2109:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:122:28, :127:22, :208:28, :217:31, :240:24, :261:26, :276:39, :280:26, :297:29, :304:22, :312:22, :330:24, :352:47, :353:46, :357:24, :360:34, :364:28, :379:35, :411:47, :416:24, :420:34, :460:24, :464:26, :516:24, :528:41, :568:24, :601:42, :602:{22,28}, :611:47, :612:31, :616:24, :618:24, :665:30, :706:{21,29}, :708:24, :760:30, :836:51, :855:30, :859:24, :877:27, :879:20, :882:20, :982:34
  wire [3:0]       _GEN_85 =
    _GEN_11 | ~(_GEN_51 | ~(instruction_flags[3])) ? instruction_regN : instruction_regD;	// <stdin>:2157:20, src/main/scala/gba/cpu/Control.scala:122:28, :217:31, :460:24, :760:30, :807:42, :836:51, :855:30, :860:33
  wire [15:0][3:0] _GEN_86 =
    {{_GEN_85},
     {_GEN_85},
     {4'hE},
     {_GEN_85},
     {instruction_regN},
     {(|(stage[2:1])) ? regNextIndex : instruction_regN},
     {_GEN_85},
     {instruction_regD},
     {4'hE},
     {instruction_regD},
     {instruction_regN},
     {_GEN_16 ? instruction_regN : instruction_regD},
     {instruction_regD},
     {instruction_regD},
     {instruction_regD},
     {4'hE}};	// <stdin>:1645:42, :1893:20, :1989:20, :2013:20, :2037:20, :2085:20, :2133:20, src/main/scala/gba/cpu/Control.scala:122:28, :127:22, :208:28, :217:31, :240:24, :330:24, :357:24, :379:35, :416:24, :460:24, :516:24, :568:24, :604:31, :639:31, :665:30, :706:{21,29}, :710:33, :760:30, :911:27
  assign io_signals_regWriteIndex_0 = _GEN_86[instruction_kind];	// <stdin>:1893:20, :1989:20, :2013:20, :2037:20, :2085:20, :2133:20, src/main/scala/gba/cpu/Control.scala:122:28, :208:28, :217:31, :240:24, :330:24, :357:24, :416:24, :460:24, :516:24, :568:24, :604:31, :706:29, :760:30, :911:27
  wire             _GEN_87 = _GEN_12 & (_GEN_51 | _GEN_80 & ~(instruction_flags[3]));	// <stdin>:1635:5, :2181:20, src/main/scala/gba/cpu/Control.scala:122:28, :203:22, :217:31, :460:24, :807:42, :826:69, :836:{29,51}, :846:28, :855:30, :945:24, :982:34
  wire             _GEN_88 =
    _GEN_64 | (_GEN_10 ? _GEN_51 : _GEN_11 ? (|stage) & ~(|counter) : _GEN_87);	// <stdin>:2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:127:22, :129:20, :167:27, :168:25, :203:22, :217:31, :460:24, :691:25, :715:30, :773:{21,29}, :786:34, :855:30, :958:29
  wire             dispatch =
    ~execute
    | (_GEN_0
         ? _GEN_25
         : _GEN_81
           | (_GEN_3
                ? _GEN_32
                : _GEN_4
                    ? _GEN_25
                    : _GEN_5 ? _GEN_32 : _GEN_6 ? _GEN_52 : _GEN_65 ? _GEN_25 : _GEN_88));	// <stdin>:1893:20, :1965:20, :1989:20, :2013:20, :2037:20, src/main/scala/gba/cpu/Control.scala:128:30, :183:28, :194:27, :195:31, :216:18, :217:31, :240:24, :247:22, :285:22, :330:24, :357:24, :416:24, :460:24, :516:24, :921:51, :958:29, :959:14, :982:34
  always @(posedge clock) begin	// src/main/scala/gba/cpu/Control.scala:98:7
    automatic logic _GEN_89;	// src/main/scala/gba/cpu/Control.scala:144:27
    automatic logic _GEN_90;	// src/main/scala/gba/cpu/Control.scala:148:27
    automatic logic _GEN_91;	// src/main/scala/gba/cpu/Control.scala:137:60, :143:21, :144:60
    automatic logic _GEN_92;	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
    automatic logic _GEN_93;	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
    _GEN_89 = io_fiq & ~io_currentStatus_fiqDisable;	// src/main/scala/gba/cpu/Control.scala:144:{27,30}
    _GEN_90 = io_irq & ~io_currentStatus_irqDisable;	// src/main/scala/gba/cpu/Control.scala:148:{27,30}
    _GEN_91 = (&io_nextInstruction_condition) | ~(_GEN_89 | _GEN_90);	// src/main/scala/gba/cpu/Control.scala:137:{42,60}, :143:21, :144:{27,60}, :145:26, :148:{27,60}, :149:26, :153:21
    _GEN_92 = io_enable & dispatch;	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60, :216:18, :217:31, :959:14
    _GEN_93 = _GEN_92 & _GEN_91;	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60, :143:21, :144:60
    if (reset) begin	// src/main/scala/gba/cpu/Control.scala:98:7
      instruction_kind <= 4'h0;	// <stdin>:1641:5, src/main/scala/gba/cpu/Control.scala:122:28
      instruction_condition <= 4'hE;	// <stdin>:1645:42, src/main/scala/gba/cpu/Control.scala:122:28
      instruction_opcode <= 4'h1;	// <stdin>:1639:39, src/main/scala/gba/cpu/Control.scala:122:28
      stage <= 3'h0;	// src/main/scala/gba/cpu/Control.scala:127:22
    end
    else begin	// src/main/scala/gba/cpu/Control.scala:98:7
      if (_GEN_92) begin	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
        instruction_kind <= _GEN_91 ? io_nextInstruction_kind : 4'h0;	// <stdin>:1641:5, src/main/scala/gba/cpu/Control.scala:122:28, :137:60, :143:21, :144:60
        instruction_condition <= _GEN_91 ? io_nextInstruction_condition : 4'hE;	// <stdin>:1645:42, src/main/scala/gba/cpu/Control.scala:122:28, :137:60, :143:21, :144:60
        instruction_opcode <=
          (&io_nextInstruction_condition)
            ? io_nextInstruction_opcode
            : _GEN_89 ? 4'h7 : _GEN_90 ? 4'h6 : io_nextInstruction_opcode;	// src/main/scala/gba/cpu/Control.scala:122:28, :137:{42,60}, :143:21, :144:{27,60}, :146:28, :148:{27,60}, :150:28, :153:21
      end
      if (io_enable) begin	// src/main/scala/gba/cpu/Control.scala:99:14
        if (dispatch)	// src/main/scala/gba/cpu/Control.scala:216:18, :217:31, :959:14
          stage <= 3'h0;	// src/main/scala/gba/cpu/Control.scala:127:22
        else if (execute) begin	// src/main/scala/gba/cpu/Control.scala:982:34
          automatic logic [15:0][2:0] _GEN_94 =
            {{stage},
             {stage},
             {_GEN_15 ? stage + 3'h1 : _GEN_16 ? stage + 3'h1 : stage},
             {_GEN_80 & instruction_flags[3]
                ? stage + 3'h1
                : _GEN_74 ? 3'h2 : _GEN_72 ? stage + 3'h1 : stage},
             {_GEN_16 ? stage + 3'h1 : _GEN_15 ? stage + 3'h1 : stage},
             {_GEN_61
                ? stage
                  + {1'h0,
                     (|(regCount[4:1])) & (|(instruction_immediate[15:0])) ? 2'h1 : 2'h2}
                : _GEN_16 ? stage + 3'h1 : _GEN_15 ? stage + 3'h1 : stage},
             {stage},
             {stage},
             {_GEN_15 ? stage + 3'h1 : _GEN_16 ? stage + 3'h1 : stage},
             {_GEN_15
                ? stage + 3'h1
                : _GEN_16 ? stage + 3'h1 : _GEN_18 ? stage + 3'h1 : stage},
             {_GEN_15 ? stage + 3'h1 : stage},
             {_GEN_15 ? stage + 3'h1 : _GEN_16 ? stage + 3'h1 : stage},
             {_GEN_15 ? stage + 3'h1 : stage},
             {stage},
             {stage},
             {_GEN_15 ? stage + 3'h1 : _GEN_16 ? stage + 3'h1 : stage}};	// <stdin>:1635:5, :1893:20, :1965:20, :1989:20, :2013:20, :2037:20, :2061:20, :2133:20, :2157:20, :2181:20, :2205:20, src/main/scala/gba/cpu/Control.scala:122:28, :127:22, :128:30, :168:25, :217:31, :240:24, :276:39, :280:26, :330:24, :357:24, :416:24, :460:24, :516:24, :568:24, :636:44, :637:36, :638:32, :641:30, :665:30, :680:47, :691:34, :695:28, :697:{29,39,45}, :738:30, :760:30, :807:42, :815:{29,49}, :826:{51,69}, :832:21, :836:{29,51}, :846:28, :969:28, :976:{15,24}, :982:34
          stage <= _GEN_94[instruction_kind];	// <stdin>:1893:20, :1965:20, :1989:20, :2013:20, :2037:20, :2061:20, :2133:20, :2157:20, :2181:20, :2205:20, src/main/scala/gba/cpu/Control.scala:122:28, :127:22, :128:30, :168:25, :217:31, :240:24, :330:24, :357:24, :416:24, :460:24, :516:24, :568:24, :680:47, :760:30, :836:51
        end
      end
    end
    if (_GEN_93) begin	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
      instruction_regN <= io_nextInstruction_regN;	// src/main/scala/gba/cpu/Control.scala:122:28
      instruction_regD <= io_nextInstruction_regD;	// src/main/scala/gba/cpu/Control.scala:122:28
      instruction_regS <= io_nextInstruction_regS;	// src/main/scala/gba/cpu/Control.scala:122:28
      instruction_regM <= io_nextInstruction_regM;	// src/main/scala/gba/cpu/Control.scala:122:28
    end
    if (~execute | _GEN_71) begin	// src/main/scala/gba/cpu/Control.scala:130:32, :132:20, :183:28, :216:18, :217:31, :982:34
      if (_GEN_93)	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
        instruction_immediate <= io_nextInstruction_immediate;	// src/main/scala/gba/cpu/Control.scala:122:28
    end
    else if (_GEN_10) begin	// <stdin>:2133:20
      if (_GEN_18 & io_enable)	// src/main/scala/gba/cpu/Control.scala:240:24, :701:29
        instruction_immediate <=
          {8'h0, instruction_immediate[15:0] & ~(16'h1 << regNextIndex)};	// src/main/scala/gba/cpu/Control.scala:122:28, :636:44, :639:31, :703:{33,44,47,53}, :878:25
      else if (_GEN_93)	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
        instruction_immediate <= io_nextInstruction_immediate;	// src/main/scala/gba/cpu/Control.scala:122:28
    end
    else if (_GEN_69 & (|counter) & io_enable)	// src/main/scala/gba/cpu/Control.scala:129:20, :132:20, :178:24, :217:31, :691:25, :773:29, :783:32, :786:34
      instruction_immediate <=
        {8'h0, instruction_immediate[15:0] & ~(16'h1 << regNextIndex_1)};	// src/main/scala/gba/cpu/Control.scala:122:28, :703:53, :733:44, :736:31, :794:{35,46,49,55}, :878:25
    else if (_GEN_93)	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
      instruction_immediate <= io_nextInstruction_immediate;	// src/main/scala/gba/cpu/Control.scala:122:28
    if (_GEN_93)	// src/main/scala/gba/cpu/Control.scala:122:28, :132:20, :135:21, :137:60
      instruction_flags <= io_nextInstruction_flags;	// src/main/scala/gba/cpu/Control.scala:122:28
    if (~(io_enable & execute) | _GEN_71) begin	// src/main/scala/gba/cpu/Control.scala:129:20, :130:32, :132:20, :134:13, :217:31, :982:34
    end
    else if (_GEN_10) begin	// <stdin>:2133:20
      if (_GEN_20)	// src/main/scala/gba/cpu/Control.scala:171:25, :240:24, :953:27
        counter <= counter - 5'h1;	// src/main/scala/gba/cpu/Control.scala:129:20, :690:34
      else if (_GEN_15)	// src/main/scala/gba/cpu/Control.scala:240:24
        counter <= ((|(instruction_immediate[15:0])) ? regCount : 5'h1) - 5'h1;	// src/main/scala/gba/cpu/Control.scala:122:28, :129:20, :636:44, :637:36, :638:32, :660:{29,59}
    end
    else if (_GEN_11) begin	// <stdin>:2157:20
      if (|stage)	// src/main/scala/gba/cpu/Control.scala:127:22, :773:21
        counter <= counter - 5'h1;	// src/main/scala/gba/cpu/Control.scala:129:20, :785:34
      else if (_GEN_15)	// src/main/scala/gba/cpu/Control.scala:240:24
        counter <= (regListEmpty_1 ? 5'h1 : regCount_1) - 5'h1;	// src/main/scala/gba/cpu/Control.scala:129:20, :660:29, :734:36, :735:32, :755:{29,59}
    end
    if (_GEN_15 & io_enable)	// src/main/scala/gba/cpu/Control.scala:238:29, :240:24, :242:30, :244:26
      entryThumb <= io_currentStatus_thumb;	// src/main/scala/gba/cpu/Control.scala:238:29
  end // always @(posedge)
  assign io_signals_advancePipeline =
    ~execute
    | (_GEN_0
         ? _GEN_24
         : _GEN_81
           | (_GEN_3
                ? _GEN_32
                : _GEN_4
                    ? _GEN_25
                    : _GEN_5 ? _GEN_32 : _GEN_6 ? _GEN_52 : _GEN_65 ? _GEN_24 : _GEN_88));	// <stdin>:1893:20, :1965:20, :1989:20, :2013:20, :2037:20, src/main/scala/gba/cpu/Control.scala:98:7, :128:30, :183:28, :194:27, :195:31, :216:18, :217:31, :240:24, :247:22, :285:22, :330:24, :357:24, :416:24, :460:24, :516:24, :921:51, :956:24, :958:29, :970:24, :982:34
  assign io_signals_flushPipeline =
    execute
    & (_GEN_0
         ? _GEN_15
         : _GEN_1
             ? _GEN_27
             : _GEN_2
                 ? _GEN_30
                 : _GEN_3
                     ? ~_GEN_15 & _GEN_16 & _GEN_33
                     : _GEN_4
                         ? ~_GEN_23 & _GEN_18 & (&instruction_regD)
                         : ~(_GEN_5 | _GEN_6)
                           & (_GEN_65
                                ? _GEN_15
                                : ~_GEN_64 & _GEN_63 & (&io_signals_regWriteIndex_0)));	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :168:25, :216:18, :217:31, :240:24, :247:22, :261:26, :285:22, :330:24, :357:24, :516:24, :715:30, :717:{39,49}, :916:28, :921:{37,51}, :956:24, :970:24, :982:34
  assign io_signals_startException = execute & _GEN_0 & _GEN_15;	// <stdin>:1893:20, src/main/scala/gba/cpu/Control.scala:98:7, :169:26, :216:18, :217:31, :240:24, :982:34
  assign io_signals_pcNext =
    ~execute
    | (_GEN_0
         ? _GEN_19
         : _GEN_1
             ? ~_GEN_27
             : _GEN_2
                 ? ~_GEN_30
                 : _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6
                     ? _GEN_15
                     : _GEN_65
                         ? _GEN_19
                         : _GEN_64
                           | (_GEN_10
                                ? (_GEN_51
                                     ? ~((&io_signals_regWriteIndex_0) | _GEN_61)
                                       & _GEN_15
                                     : ~_GEN_61 & _GEN_15)
                                : _GEN_11
                                    ? ~((|stage) & ~(|counter)) & _GEN_15
                                    : _GEN_77));	// <stdin>:1635:5, :1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :127:22, :129:20, :168:25, :183:28, :196:26, :216:18, :217:31, :240:24, :330:24, :460:24, :516:24, :641:30, :680:47, :691:{25,34}, :695:28, :715:30, :717:{39,49}, :738:30, :773:{21,29}, :786:34, :790:28, :826:69, :921:{37,51}, :952:20, :964:20, :982:34
  assign io_signals_addressSource = execute ? _GEN_79[instruction_kind] : 3'h1;	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :168:25, :216:18, :217:31, :240:24, :280:26, :330:24, :357:24, :416:24, :460:24, :516:24, :715:30, :773:29, :921:51, :953:27, :982:34
  assign io_signals_regBankMode =
    execute & _GEN_0 & _GEN_15 ? _GEN_14[instruction_opcode[2:0]] : io_currentStatus_mode;	// <stdin>:1893:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :172:23, :216:18, :217:31, :219:64, :229:58, :240:24, :256:33, :982:34
  assign io_signals_regReadA = _GEN_76[instruction_kind];	// <stdin>:1893:20, :2061:20, :2205:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :217:31, :240:24, :330:24, :357:24, :416:24, :516:24, :568:24, :665:30, :760:30, :909:22
  assign io_signals_regReadB =
    _GEN_0
      ? 4'hF
      : _GEN_2
          ? instruction_regM
          : _GEN_3
              ? (_GEN_15 ? instruction_regS : instruction_regM)
              : _GEN_4
                  ? (~_GEN_15 | instruction_flags[2]
                       ? instruction_regM
                       : instruction_regN)
                  : _GEN_5
                      ? (_GEN_44 ? instruction_regM : instruction_regN)
                      : _GEN_6
                          ? instruction_regN
                          : _GEN_9
                              ? instruction_regM
                              : _GEN_74 ? instruction_regS : instruction_regN;	// <stdin>:1893:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2109:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :137:42, :217:31, :240:24, :261:26, :311:26, :330:24, :332:30, :353:46, :357:24, :360:34, :416:24, :420:34, :460:24, :612:31, :815:49, :826:{51,69}, :829:28
  assign io_signals_regReadC =
    _GEN_5 ? instruction_regD : _GEN_6 ? instruction_regM : regNextIndex_1;	// <stdin>:2013:20, :2037:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :217:31, :416:24, :460:24, :736:31
  assign io_signals_regWriteIndex = io_signals_regWriteIndex_0;	// src/main/scala/gba/cpu/Control.scala:98:7, :217:31, :240:24
  assign io_signals_regWriteEnable =
    execute
    & (_GEN_0
         ? _GEN_17
         : _GEN_1
             ? _io_signals_regWriteEnable_T
             : _GEN_2
                 ? _io_signals_regWriteEnable_T_1
                 : _GEN_3
                     ? ~_GEN_15 & _GEN_16 & _io_signals_regWriteEnable_T_2
                     : _GEN_4
                         ? ~_GEN_15 & (_GEN_16 ? instruction_flags[0] : _GEN_18)
                         : _GEN_5
                             ? ~_GEN_15 & _GEN_16 & instruction_flags[0]
                             : _GEN_6
                                 ? _GEN_52
                                 : _GEN_7
                                     ? ~_GEN_15 & _GEN_16 & instruction_flags[0]
                                     : _GEN_13
                                         ? _GEN_32
                                         : _GEN_8 | ~_GEN_9
                                           & (_GEN_10
                                                ? (|(stage[2:1])) | _GEN_16
                                                  & instruction_flags[0]
                                                : _GEN_11
                                                    ? _GEN_16 & instruction_flags[0]
                                                    : _GEN_12 & (_GEN_51 | _GEN_80)));	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2061:20, :2085:20, :2109:20, :2133:20, :2157:20, :2181:20, :2205:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :127:22, :177:26, :182:28, :194:27, :195:31, :216:18, :217:31, :240:24, :261:26, :264:36, :330:24, :355:47, :357:24, :379:35, :414:47, :416:24, :460:24, :512:42, :516:24, :568:24, :605:32, :622:26, :630:47, :665:30, :668:34, :706:{21,29}, :711:34, :727:47, :760:30, :763:34, :836:{29,51}, :855:30, :858:34, :907:45, :912:28, :982:34
  assign io_signals_regUserReadC = execute & ~_GEN_70 & _GEN_69 & instruction_flags[1];	// src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :178:24, :216:18, :217:31, :728:39, :773:29, :783:32, :982:34
  assign io_signals_regUserWrite =
    execute & ~_GEN_62 & _GEN_10 & (|(stage[2:1])) & instruction_flags[1];	// <stdin>:2133:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :127:22, :179:24, :216:18, :217:31, :631:39, :706:21, :982:34
  assign io_signals_cpsrUpdateCond = io_signals_cpsrUpdateCond_0;	// src/main/scala/gba/cpu/Control.scala:98:7, :180:26, :216:18, :217:31
  assign io_signals_cpsrUpdateThumb =
    execute & ~_GEN_53 & _GEN_7 & _GEN_15 & instruction_flags[1];	// <stdin>:2061:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :181:27, :216:18, :217:31, :240:24, :513:46, :982:34
  assign io_signals_cpsrUpdateFields =
    ~execute | _GEN_56 | ~_GEN_9 | instruction_flags[0]
      ? 2'h0
      : {instruction_opcode[3], instruction_opcode[0]};	// <stdin>:2109:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :182:28, :183:28, :216:18, :217:31, :528:41, :610:42, :622:26, :625:{42,61,84}, :982:34
  assign io_signals_spsrUpdateFields =
    ~execute | _GEN_56 | ~(_GEN_9 & instruction_flags[0])
      ? 2'h0
      : {instruction_opcode[3], instruction_opcode[0]};	// <stdin>:2109:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :183:28, :216:18, :217:31, :528:41, :610:42, :622:26, :623:{36,42,61,84}, :982:34
  assign io_signals_cpsrRestore =
    execute & ~_GEN_0
    & (_GEN_1 | _GEN_2
         ? _GEN_26
         : _GEN_3
             ? ~_GEN_15 & _GEN_16 & _GEN_26
             : ~(_GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_13 | _GEN_8 | _GEN_9) & _GEN_63
               & (&io_signals_regWriteIndex_0) & instruction_flags[1]);	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2061:20, :2085:20, :2109:20, :2205:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :168:25, :180:26, :184:23, :216:18, :217:31, :240:24, :261:26, :330:24, :631:39, :715:30, :717:{39,49}, :916:{37,64}, :982:34
  assign io_signals_cpsrFromMultiply =
    execute & ~_GEN_73 & _GEN_12 & _GEN_80 & instruction_flags[0];	// <stdin>:2181:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :185:28, :198:35, :216:18, :217:31, :804:45, :836:29, :982:34
  assign io_signals_busB = _GEN_84[instruction_kind];	// <stdin>:1893:20, :1917:20, :1989:20, :2013:20, :2037:20, :2085:20, :2109:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :208:28, :217:31, :240:24, :304:22, :312:22, :330:24, :357:24, :416:24, :460:24, :516:24, :568:24, :602:22, :612:31, :706:29, :760:30
  assign io_signals_immediate =
    _GEN_0
      ? (_GEN_15
           ? {27'h0,
              (&(instruction_opcode[2:0]))
                ? 5'h1C
                : instruction_opcode[2:0] == 3'h6
                    ? 5'h18
                    : instruction_opcode[2:0] == 3'h5
                        ? 5'h10
                        : {1'h0,
                           instruction_opcode[2:0] == 3'h4
                             ? 4'hC
                             : instruction_opcode[2:0] == 3'h3
                                 ? 4'h8
                                 : {1'h0, instruction_opcode[2:0] == 3'h2, 2'h0}}}
           : {29'h0,
              instruction_opcode[2:0] == 3'h3 | instruction_opcode[2:0] == 3'h2
                ? (entryThumb ? 3'h2 : 3'h4)
                : {~entryThumb, 2'h0}})
      : _GEN_1
          ? (instruction_flags[1]
               ? {{9{instruction_immediate[10]}}, instruction_immediate[10:0], 12'h0}
               : {24'h0, instruction_immediate[7:0]})
          : _GEN_66
              ? {8'h0, instruction_immediate}
              : _GEN_7
                  ? (_GEN_15
                       ? (instruction_flags[1]
                            ? 32'h1
                            : instruction_flags[2]
                                ? {{20{instruction_immediate[10]}},
                                   instruction_immediate[10:0],
                                   1'h0}
                                : {{6{instruction_immediate[23]}},
                                   instruction_immediate,
                                   2'h0})
                       : 32'h4)
                  : _GEN_13
                      ? (_GEN_15 ? {20'h0, instruction_immediate[10:0], 1'h0} : 32'h1)
                      : _GEN_9
                          ? {24'h0, instruction_immediate[7:0]}
                          : {27'h0,
                             _GEN_10
                               ? (_GEN_16
                                    ? ((|(instruction_immediate[15:0]))
                                         ? regCount
                                         : 5'h10)
                                    : instruction_flags[2]
                                        ? {4'h0, instruction_flags[3]}
                                        : ((|(instruction_immediate[15:0]))
                                             ? regCount
                                             : 5'h10) - {4'h0, ~(instruction_flags[3])})
                               : _GEN_16
                                   ? (regListEmpty_1 ? 5'h10 : regCount_1)
                                   : instruction_flags[2]
                                       ? {4'h0, instruction_flags[3]}
                                       : (regListEmpty_1 ? 5'h10 : regCount_1)
                                         - {4'h0, ~(instruction_flags[3])}};	// <stdin>:1635:5, :1641:5, :1893:20, :1917:20, :2061:20, :2109:20, :2133:20, :2205:20, :2356:26, :2378:26, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :150:49, :217:31, :219:64, :220:46, :238:29, :240:24, :250:31, :275:{60,108}, :276:{33,39}, :278:{33,39}, :296:{32,45}, :297:29, :299:{29,53}, :302:{29,35,40,65,93}, :357:24, :513:46, :514:47, :516:24, :518:34, :521:33, :527:38, :528:{35,41}, :529:{23,48}, :534:{35,41}, :535:{23,49}, :536:40, :554:33, :568:24, :572:{31,55}, :612:31, :615:{29,53}, :632:40, :633:46, :636:44, :637:36, :638:32, :641:30, :646:35, :648:{16,47,50}, :665:30, :670:{29,35}, :729:40, :730:46, :734:36, :735:32, :738:30, :741:35, :743:{16,47,50}, :760:30, :765:{29,35}, :878:25, :982:34
  assign io_signals_aluOpcode = _GEN_82[instruction_kind];	// <stdin>:1893:20, :1989:20, :2013:20, :2037:20, :2061:20, :2133:20, :2157:20, :2205:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :168:25, :217:31, :240:24, :357:24, :416:24, :460:24, :516:24, :568:24, :603:27, :621:27, :706:29, :760:30, :910:23
  assign io_signals_aluOutAlign4 =
    execute & ~_GEN_0
    & (_GEN_1
         ? instruction_flags[2]
         : _GEN_2
             ? instruction_flags[2]
             : _GEN_3 & ~_GEN_15 & _GEN_16 & instruction_flags[2]);	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :180:26, :189:24, :216:18, :217:31, :240:24, :261:26, :330:24, :914:{26,46}, :982:34
  assign io_signals_aluInAAlign4 =
    execute & ~_GEN_40
    & (_GEN_4
         ? (_GEN_15
              ? instruction_flags[2] & instruction_flags[6]
              : _GEN_39 & instruction_flags[6])
         : _GEN_5
           & (_GEN_15
                ? instruction_flags[2] & instruction_flags[6]
                : _GEN_47 & instruction_flags[6]));	// <stdin>:1989:20, :2013:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :190:24, :192:26, :210:29, :216:18, :217:31, :240:24, :353:46, :357:24, :360:34, :379:35, :412:46, :416:24, :420:34, :440:35, :872:41, :877:27, :900:26, :982:34
  assign io_signals_shiftKind =
    ~execute | _GEN_0
      ? 3'h0
      : _GEN_1
          ? (instruction_flags[1] ? 3'h0 : 3'h3)
          : _GEN_2
              ? (~_GEN_28 | _GEN_29 | instruction_immediate[1:0] != 2'h3
                   ? {1'h0, instruction_immediate[1:0]}
                   : 3'h4)
              : _GEN_3
                  ? (_GEN_15 | ~_GEN_16 ? 3'h0 : {1'h0, instruction_immediate[1:0]})
                  : _GEN_4
                      ? (_GEN_15
                           ? (_GEN_36
                                ? 3'h0
                                : ~_GEN_34 | _GEN_35 | instruction_immediate[1:0] != 2'h3
                                    ? {1'h0, instruction_immediate[1:0]}
                                    : 3'h4)
                           : _GEN_16
                               ? (~(instruction_flags[0]) | instruction_flags[3]
                                    ? 3'h0
                                    : ~_GEN_37 | _GEN_38
                                      | instruction_immediate[1:0] != 2'h3
                                        ? {1'h0, instruction_immediate[1:0]}
                                        : 3'h4)
                               : _GEN_18 ? {2'h1, ~(instruction_flags[4])} : 3'h0)
                      : _GEN_5
                          ? (_GEN_15
                               ? (_GEN_43
                                    ? 3'h0
                                    : ~_GEN_41 | _GEN_42
                                      | instruction_immediate[1:0] != 2'h3
                                        ? {1'h0, instruction_immediate[1:0]}
                                        : 3'h4)
                               : _GEN_48
                                   ? 3'h0
                                   : ~_GEN_45 | _GEN_46
                                     | instruction_immediate[1:0] != 2'h3
                                       ? {1'h0, instruction_immediate[1:0]}
                                       : 3'h4)
                          : (_GEN_6
                               ? _GEN_15 | _GEN_20 | ~_GEN_51
                               : _GEN_55 | ~(_GEN_9 & instruction_flags[1]))
                              ? 3'h0
                              : 3'h3;	// <stdin>:1635:5, :1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2109:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :127:22, :171:25, :183:28, :191:21, :192:26, :216:18, :217:31, :240:24, :296:{32,45}, :297:29, :310:{72,87}, :313:27, :315:{30,39}, :316:29, :330:24, :339:{76,91}, :351:44, :352:47, :355:47, :357:24, :360:34, :379:35, :396:{31,37}, :416:24, :420:34, :440:35, :460:24, :611:47, :612:31, :613:29, :877:27, :884:{70,85}, :885:25, :887:{28,37}, :888:28, :953:27, :969:28, :982:34
  assign io_signals_shiftImmediate = execute ? _GEN_68[instruction_kind] : 6'h0;	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2109:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :183:28, :192:26, :216:18, :217:31, :296:45, :315:39, :357:24, :416:24, :529:23, :612:31, :982:34
  assign io_signals_shiftDoLatch = execute & ~_GEN_31 & _GEN_3 & _GEN_15;	// <stdin>:1965:20, src/main/scala/gba/cpu/Control.scala:98:7, :193:24, :216:18, :217:31, :240:24, :982:34
  assign io_signals_shiftUseLatched = execute & ~_GEN_31 & _GEN_3 & _GEN_32;	// <stdin>:1965:20, src/main/scala/gba/cpu/Control.scala:98:7, :193:24, :194:27, :216:18, :217:31, :330:24, :982:34
  assign io_signals_shiftByAddressAlign =
    execute & ~_GEN_40 & (_GEN_4 ? _GEN_25 : ~_GEN_5 & _GEN_6 & _GEN_52);	// <stdin>:1989:20, :2013:20, :2037:20, src/main/scala/gba/cpu/Control.scala:98:7, :195:31, :210:29, :216:18, :217:31, :240:24, :247:22, :285:22, :357:24, :460:24, :982:34
  assign io_signals_multiplyEnable = execute & ~_GEN_73 & _GEN_77;	// src/main/scala/gba/cpu/Control.scala:98:7, :196:26, :198:35, :216:18, :217:31, :826:69, :982:34
  assign io_signals_multiplySigned = instruction_flags[2];	// src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :806:44
  assign io_signals_multiplyLoadAccumulator = execute & ~_GEN_73 & _GEN_12 & _GEN_72;	// <stdin>:2181:20, src/main/scala/gba/cpu/Control.scala:98:7, :198:35, :216:18, :217:31, :815:29, :982:34
  assign io_signals_multiplyAccumulate = instruction_flags[1];	// src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :805:48
  assign io_signals_multiplyLong = instruction_flags[3];	// src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :807:42
  assign io_signals_memRequest =
    ~execute
    | (_GEN_0
         ? _GEN_24
         : _GEN_81
           | (_GEN_3
                ? _GEN_32
                : _GEN_4
                    ? _GEN_15 | ~_GEN_16 & _GEN_18
                    : _GEN_5
                        ? _GEN_17
                        : _GEN_6
                            ? _GEN_23 | ~_GEN_18 & _GEN_51
                            : _GEN_65
                                ? _GEN_24
                                : _GEN_64
                                  | (_GEN_10
                                       ? _GEN_51 | (_GEN_20 ? (|counter) : _GEN_15)
                                       : _GEN_11 | _GEN_87)));	// <stdin>:1893:20, :1965:20, :1989:20, :2013:20, :2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :128:30, :129:20, :168:25, :171:25, :183:28, :191:21, :194:27, :203:22, :216:18, :217:31, :240:24, :264:36, :330:24, :357:24, :369:32, :416:24, :460:24, :467:32, :483:32, :516:24, :641:30, :680:47, :691:{25,34}, :715:30, :717:49, :773:29, :855:30, :921:51, :937:24, :953:27, :956:24, :970:24, :982:34
  assign io_signals_memSequential =
    ~execute
    | (_GEN_0
         ? _GEN_19
         : _GEN_1
             ? ~_GEN_27
             : _GEN_2
                 ? ~_GEN_30
                 : _GEN_3
                     ? ~_GEN_15 & _GEN_16 & ~_GEN_33
                     : _GEN_4
                         ? ~_GEN_23 & _GEN_18 & ~(&instruction_regD)
                         : ~_GEN_5
                           & (_GEN_6
                                ? _GEN_52
                                : _GEN_65
                                    ? _GEN_19
                                    : _GEN_64
                                      | (_GEN_10
                                           ? (_GEN_51
                                                ? ~(&io_signals_regWriteIndex_0)
                                                : _GEN_20 & (|counter))
                                           : _GEN_11 ? (|stage) & (|counter) : _GEN_87)));	// <stdin>:1635:5, :1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :127:22, :129:20, :168:25, :171:25, :183:28, :195:31, :203:22, :216:18, :217:31, :240:24, :247:22, :261:26, :285:22, :330:24, :357:24, :370:35, :400:46, :416:24, :460:24, :516:24, :641:30, :680:47, :691:{25,34}, :715:30, :717:{39,49}, :738:30, :773:{21,29}, :786:34, :855:30, :916:28, :921:{37,51}, :938:27, :946:27, :952:20, :953:27, :956:24, :957:27, :964:20, :970:24, :971:27, :982:34
  assign io_signals_memWrite =
    execute & ~_GEN_49
    & (_GEN_5
         ? _GEN_15
         : _GEN_6
             ? _GEN_32
             : ~(_GEN_58 | _GEN_10) & _GEN_11 & ((|stage) ? (|counter) : _GEN_15));	// <stdin>:2013:20, :2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :127:22, :129:20, :194:27, :207:19, :208:28, :216:18, :217:31, :240:24, :330:24, :357:24, :416:24, :460:24, :516:24, :568:24, :691:25, :715:30, :738:30, :773:{21,29}, :786:34, :921:51, :954:22, :982:34
  assign io_signals_memWidth =
    execute
      ? (_GEN_0 | _GEN_1 | _GEN_2 | _GEN_3
           ? _GEN_22
           : _GEN_4
               ? (_GEN_15 ? instruction_opcode[1:0] : _GEN_22)
               : _GEN_5
                   ? (_GEN_15
                        ? instruction_opcode[1:0]
                        : io_nextStatus_thumb ? 2'h1 : 2'h2)
                   : _GEN_6
                       ? (_GEN_23 ? instruction_opcode[1:0] : _GEN_22)
                       : (_GEN_7 | _GEN_13 | _GEN_8 | _GEN_9
                            ? io_nextStatus_thumb
                            : _GEN_10
                                ? (_GEN_51 ? io_nextStatus_thumb : _GEN_20 & _GEN_59)
                                : _GEN_11 ? (|stage) & _GEN_59 : io_nextStatus_thumb)
                           ? 2'h1
                           : 2'h2)
      : io_nextStatus_thumb ? 2'h1 : 2'h2;	// <stdin>:1893:20, :1917:20, :1941:20, :1965:20, :1989:20, :2013:20, :2037:20, :2061:20, :2085:20, :2109:20, :2133:20, :2157:20, :2205:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :127:22, :171:25, :216:18, :217:31, :240:24, :349:65, :357:24, :372:30, :409:65, :416:24, :433:30, :458:65, :460:24, :470:30, :486:30, :516:24, :568:24, :641:30, :680:47, :687:28, :691:34, :715:30, :717:49, :738:30, :773:{21,29}, :780:28, :786:34, :836:51, :855:30, :936:{22,28}, :944:22, :953:27, :955:{22,28}, :956:24, :969:{22,28}, :970:24, :982:34
  assign io_signals_memProt_data =
    execute & ~_GEN_40
    & (_GEN_66
         ? _GEN_15
         : _GEN_6 ? _GEN_17 : ~_GEN_58 & (_GEN_10 ? _GEN_20 | _GEN_15 : _GEN_11));	// <stdin>:2037:20, :2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :171:25, :206:24, :208:28, :210:29, :216:18, :217:31, :240:24, :264:36, :357:24, :460:24, :641:30, :680:47, :688:32, :953:27, :982:34
  assign io_signals_memLock = execute & ~_GEN_50 & _GEN_6 & _GEN_19;	// <stdin>:2037:20, src/main/scala/gba/cpu/Control.scala:98:7, :207:19, :216:18, :217:31, :240:24, :964:20, :982:34
  assign io_signals_latchMemReadData =
    execute & ~_GEN_40
    & (_GEN_4 ? _GEN_32 : ~_GEN_5 & (_GEN_6 ? _GEN_32 : ~_GEN_58 & _GEN_10 & _GEN_20));	// <stdin>:1989:20, :2013:20, :2037:20, :2133:20, src/main/scala/gba/cpu/Control.scala:98:7, :171:25, :194:27, :195:31, :208:28, :210:29, :216:18, :217:31, :240:24, :330:24, :357:24, :460:24, :953:27, :982:34
  assign io_signals_memReadDataSigned =
    execute & ~_GEN_40 & _GEN_4 & ~_GEN_23 & _GEN_18 & instruction_flags[4];	// <stdin>:1989:20, src/main/scala/gba/cpu/Control.scala:98:7, :122:28, :210:29, :216:18, :217:31, :240:24, :247:22, :285:22, :351:44, :956:24, :970:24, :982:34
  assign io_signals_incrementerForceWord =
    execute & ~_GEN_62 & (_GEN_10 ? _GEN_20 : _GEN_11 & (|stage));	// <stdin>:2133:20, :2157:20, src/main/scala/gba/cpu/Control.scala:98:7, :127:22, :171:25, :179:24, :211:32, :216:18, :217:31, :240:24, :680:47, :773:{21,29}, :953:27, :982:34
endmodule

