// Generated by CIRCT firtool-1.62.0
module Decoder(	// src/main/scala/gba/cpu/Decoder.scala:86:7
  input         clock,	// src/main/scala/gba/cpu/Decoder.scala:86:7
                reset,	// src/main/scala/gba/cpu/Decoder.scala:86:7
                io_enable,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_thumb,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_advancePipeline,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_flushPipeline,	// src/main/scala/gba/cpu/Decoder.scala:87:14
  input  [31:0] io_readData,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_readAddress,	// src/main/scala/gba/cpu/Decoder.scala:87:14
  output [3:0]  io_decoded_kind,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_decoded_condition,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_decoded_regN,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_decoded_regD,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_decoded_regS,	// src/main/scala/gba/cpu/Decoder.scala:87:14
                io_decoded_regM,	// src/main/scala/gba/cpu/Decoder.scala:87:14
  output [23:0] io_decoded_immediate,	// src/main/scala/gba/cpu/Decoder.scala:87:14
  output [3:0]  io_decoded_opcode,	// src/main/scala/gba/cpu/Decoder.scala:87:14
  output [6:0]  io_decoded_flags	// src/main/scala/gba/cpu/Decoder.scala:87:14
);

  wire [3:0][3:0] _GEN = '{4'h2, 4'hD, 4'hA, 4'h4};	// src/main/scala/gba/cpu/Decoder.scala:158:14, :370:{20,29}, :372:20, :375:{27,36}, :377:20, :380:{27,36}, :382:20
  wire [3:0][3:0] _io_decoded_opcode_WIRE = '{4'h2, 4'h4, 4'hA, 4'hD};	// src/main/scala/gba/cpu/Decoder.scala:323:28
  reg             isNewFetch;	// src/main/scala/gba/cpu/Decoder.scala:115:27
  reg             fetchRegValid;	// src/main/scala/gba/cpu/Decoder.scala:119:30
  reg  [31:0]     fetchReg;	// src/main/scala/gba/cpu/Decoder.scala:120:21
  reg  [31:0]     decodeReg;	// src/main/scala/gba/cpu/Decoder.scala:132:22
  reg             decodeRegValid;	// src/main/scala/gba/cpu/Decoder.scala:133:31
  wire            _GEN_0 = io_flushPipeline | ~decodeRegValid;	// src/main/scala/gba/cpu/Decoder.scala:133:31, :162:{26,29}
  wire            _GEN_1 = decodeReg[27:25] == 3'h0;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :168:{13,22}
  wire            _GEN_2 = _GEN_1 & decodeReg[4] & decodeReg[7];	// src/main/scala/gba/cpu/Decoder.scala:132:22, :168:{22,45,49,54}
  wire            _GEN_3 = decodeReg[7:4] == 4'h9;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:{15,22}
  wire            _GEN_4 = _GEN_3 & decodeReg[27:23] == 5'h0;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:{22,41,46,55}
  wire            _GEN_5 = _GEN_3 & decodeReg[27:23] == 5'h1;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:{22,46}, :178:{48,62}
  wire            _GEN_6 = _GEN_3 & decodeReg[27:23] == 5'h2;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:{22,46}, :186:{48,62}
  wire            _GEN_7 = _GEN_4 | _GEN_5;	// src/main/scala/gba/cpu/Decoder.scala:170:{41,64}, :172:18, :178:{48,71}, :180:18, :186:71
  wire            _GEN_8 = decodeReg[24:23] == 2'h2;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :158:52, :210:{53,62}
  wire            _GEN_9 = _GEN_8 & ~(decodeReg[20]);	// src/main/scala/gba/cpu/Decoder.scala:132:22, :210:{62,79,82,85}
  wire            _GEN_10 = decodeReg[27:26] == 2'h0 & ~_GEN_9;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :177:25, :210:{20,29,46,49,79}
  wire            _GEN_11 = _GEN_1 & _GEN_9;	// src/main/scala/gba/cpu/Decoder.scala:168:22, :210:79, :232:47
  wire            _GEN_12 = decodeReg[7:4] == 4'h0;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :151:12, :170:15, :234:22
  wire            _GEN_13 = decodeReg[7:4] == 4'h1 & decodeReg[22:21] == 2'h1;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:15, :247:{29,48,53,62}
  wire            _GEN_14 = decodeReg[27:25] == 3'h1 & decodeReg[21:20] == 2'h2 & _GEN_8;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :158:52, :168:13, :210:62, :252:{29,52,61,78}
  wire            _GEN_15 = decodeReg[27:25] == 3'h5;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :168:13, :194:24, :258:28
  wire            _GEN_16 = decodeReg[27:26] == 2'h1;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :210:20, :247:62, :263:29
  wire            _GEN_17 = decodeReg[27:25] == 3'h4;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :168:13, :194:24, :277:28
  wire            _GEN_18 = decodeReg[15:13] == 3'h0;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :168:22, :291:{13,22}
  wire            _GEN_19 = decodeReg[12:11] != 2'h3;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :223:18, :292:{15,24}
  wire            _GEN_20 = decodeReg[15:13] == 3'h1;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :252:29, :291:13, :316:29
  wire [3:0]      _GEN_21 = {1'h0, decodeReg[10:8]};	// src/main/scala/gba/cpu/Decoder.scala:119:30, :132:22, :320:{16,21}
  wire            _GEN_22 = decodeReg[15:10] == 6'h10;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :324:{20,29}
  wire            _GEN_23 =
    decodeReg[9:6] == 4'h0 | decodeReg[9:6] == 4'h1 | decodeReg[9:6] == 4'h5
    | decodeReg[9:6] == 4'h6 | decodeReg[9:6] == 4'h8 | decodeReg[9:6] == 4'hA
    | decodeReg[9:6] == 4'hB | decodeReg[9:6] == 4'hC | decodeReg[9:6] == 4'hE
    | (&(decodeReg[9:6]));	// src/main/scala/gba/cpu/Decoder.scala:132:22, :151:12, :152:17, :172:18, :243:20, :247:29, :279:22, :332:22, :333:23, :399:29, :421:25
  wire            _io_decoded_immediate_T_18 = decodeReg[9:6] == 4'h2;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :158:14, :332:22, :333:23
  wire            _io_decoded_immediate_T_20 = decodeReg[9:6] == 4'h3;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :223:18, :332:22, :333:23
  wire            _io_decoded_immediate_T_22 = decodeReg[9:6] == 4'h4;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :323:28, :332:22, :333:23
  wire            _GEN_24 =
    _io_decoded_immediate_T_18 | _io_decoded_immediate_T_20 | _io_decoded_immediate_T_22
    | decodeReg[9:6] == 4'h7;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :248:18, :332:22, :333:23
  wire            _GEN_25 = decodeReg[9:6] == 4'h9;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:22, :332:22, :333:23
  wire            _GEN_26 = _GEN_23 | ~_GEN_24;	// src/main/scala/gba/cpu/Decoder.scala:333:23, :337:25
  wire            _GEN_27 = decodeReg[9:6] == 4'hD;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :296:37, :332:22, :333:23
  wire            _GEN_28 = decodeReg[15:10] == 6'h11;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :324:20, :363:29
  wire            _GEN_29 = decodeReg[9:8] == 2'h0;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :177:25, :365:22, :370:20
  wire            _GEN_30 = decodeReg[9:8] == 2'h1;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :247:62, :365:22, :375:27
  wire            _GEN_31 = decodeReg[9:8] == 2'h2;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :158:52, :365:22, :380:27
  wire            _GEN_32 = decodeReg[15:11] == 5'h9;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :390:{20,29}
  wire            _GEN_33 = decodeReg[15:12] == 4'h5;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :399:{20,29}
  wire            _GEN_34 = decodeReg[15:13] == 3'h3;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :291:13, :424:29
  wire            _GEN_35 = decodeReg[15:12] == 4'h8;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :243:20, :399:20, :441:29
  wire            _GEN_36 = decodeReg[15:12] == 4'h9;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :170:22, :399:20, :449:29
  wire            _GEN_37 = decodeReg[15:12] == 4'hA;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :279:22, :399:20, :457:29
  wire            _GEN_38 = decodeReg[15:8] == 8'hB0;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :471:{20,28}
  wire            _GEN_39 = decodeReg[15:12] == 4'hD;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :296:37, :399:20, :478:29
  wire            _GEN_40 = (&(decodeReg[11:8])) | decodeReg[11:8] == 4'hE;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :151:12, :152:17, :479:{15,23,43}, :481:18, :483:{30,50}, :485:18
  wire            _GEN_41 = _GEN_37 | _GEN_38;	// src/main/scala/gba/cpu/Decoder.scala:289:19, :457:{29,49}, :471:{28,52}, :478:49
  wire            _GEN_42 = decodeReg[15:12] == 4'hB & decodeReg[10:9] == 2'h2;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :158:52, :279:22, :399:20, :490:{29,48,53,61}
  wire            _GEN_43 = decodeReg[15:12] == 4'hC;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :172:18, :399:20, :504:29
  wire            _GEN_44 = decodeReg[15:11] == 5'h1C;	// src/main/scala/gba/cpu/Decoder.scala:132:22, :390:20, :514:29
  wire            _GEN_45 = (&(decodeReg[15:12])) & ~(decodeReg[11]);	// src/main/scala/gba/cpu/Decoder.scala:132:22, :159:13, :399:20, :402:17, :519:{29,49}, :521:{13,22}, :526:19
  always @(posedge clock) begin	// src/main/scala/gba/cpu/Decoder.scala:86:7
    automatic logic [31:0] currentFetch;	// src/main/scala/gba/cpu/Decoder.scala:111:25
    automatic logic        _GEN_46;	// src/main/scala/gba/cpu/Decoder.scala:122:19
    automatic logic        _GEN_47;	// src/main/scala/gba/cpu/Decoder.scala:135:19
    currentFetch =
      io_thumb
        ? {16'h0, io_readAddress[1] ? io_readData[31:16] : io_readData[15:0]}
        : io_readData;	// src/main/scala/gba/cpu/Decoder.scala:111:25, :112:{8,23,39,60}
    _GEN_46 = io_enable & ~io_advancePipeline & isNewFetch;	// src/main/scala/gba/cpu/Decoder.scala:115:27, :122:{19,23}
    _GEN_47 = io_enable & io_advancePipeline;	// src/main/scala/gba/cpu/Decoder.scala:135:19
    if (reset) begin	// src/main/scala/gba/cpu/Decoder.scala:86:7
      isNewFetch <= 1'h1;	// src/main/scala/gba/cpu/Decoder.scala:115:27
      fetchRegValid <= 1'h0;	// src/main/scala/gba/cpu/Decoder.scala:119:30
      decodeRegValid <= 1'h0;	// src/main/scala/gba/cpu/Decoder.scala:119:30, :133:31
    end
    else begin	// src/main/scala/gba/cpu/Decoder.scala:86:7
      automatic logic _GEN_48 = io_enable & io_flushPipeline;	// src/main/scala/gba/cpu/Decoder.scala:142:19
      if (io_enable)	// src/main/scala/gba/cpu/Decoder.scala:87:14
        isNewFetch <= io_advancePipeline;	// src/main/scala/gba/cpu/Decoder.scala:115:27
      fetchRegValid <= ~_GEN_48 & (_GEN_46 | fetchRegValid);	// src/main/scala/gba/cpu/Decoder.scala:119:30, :122:{19,59}, :124:19, :142:{19,40}, :143:19
      decodeRegValid <=
        ~_GEN_48 & (_GEN_47 ? isNewFetch | fetchRegValid : decodeRegValid);	// src/main/scala/gba/cpu/Decoder.scala:115:27, :119:30, :122:59, :128:29, :133:31, :135:{19,42}, :137:20, :142:{19,40}, :143:19, :144:20
    end
    if (_GEN_46)	// src/main/scala/gba/cpu/Decoder.scala:122:19
      fetchReg <= currentFetch;	// src/main/scala/gba/cpu/Decoder.scala:111:25, :120:21
    if (_GEN_47)	// src/main/scala/gba/cpu/Decoder.scala:135:19
      decodeReg <= isNewFetch ? currentFetch : fetchReg;	// src/main/scala/gba/cpu/Decoder.scala:111:25, :115:27, :120:21, :127:24, :132:22
  end // always @(posedge)
  assign io_decoded_kind =
    _GEN_0
      ? 4'h0
      : io_thumb
          ? (_GEN_18
               ? (_GEN_19 | ~(decodeReg[10]) ? 4'h2 : 4'h1)
               : _GEN_20
                   ? 4'h1
                   : _GEN_22
                       ? (_GEN_23
                            ? 4'h2
                            : _GEN_24 ? 4'h3 : _GEN_25 ? 4'h1 : _GEN_27 ? 4'hC : 4'h0)
                       : _GEN_28
                           ? (_GEN_29 | _GEN_30 | _GEN_31 ? 4'h2 : 4'h7)
                           : _GEN_32
                               ? 4'h4
                               : _GEN_33
                                   ? {3'h2,
                                      decodeReg[9]
                                        ? decodeReg[11:10] == 2'h0
                                        : ~(decodeReg[11])}
                                   : _GEN_34
                                       ? {3'h2, ~(decodeReg[11])}
                                       : _GEN_35
                                           ? {3'h2, ~(decodeReg[11])}
                                           : _GEN_36
                                               ? {3'h2, ~(decodeReg[11])}
                                               : _GEN_41
                                                   ? 4'h1
                                                   : _GEN_39
                                                       ? (_GEN_40 ? 4'h0 : 4'h7)
                                                       : _GEN_42 | _GEN_43
                                                           ? {3'h5, ~(decodeReg[11])}
                                                           : _GEN_44
                                                               ? 4'h7
                                                               : (&(decodeReg[15:12]))
                                                                   ? (decodeReg[11]
                                                                        ? 4'hD
                                                                        : 4'h1)
                                                                   : 4'h0)
          : _GEN_2
              ? (_GEN_7 ? 4'hC : _GEN_6 ? 4'h6 : {3'h2, ~(decodeReg[20])})
              : _GEN_10
                  ? (decodeReg[25] ? 4'h1 : {3'h1, decodeReg[4]})
                  : _GEN_11
                      ? (_GEN_12 ? {3'h4, decodeReg[21]} : _GEN_13 ? 4'h7 : 4'h0)
                      : _GEN_14
                          ? 4'h9
                          : _GEN_15
                              ? 4'h7
                              : _GEN_16
                                  ? {3'h2, ~(decodeReg[20])}
                                  : _GEN_17 ? {3'h5, ~(decodeReg[20])} : 4'h0;	// src/main/scala/gba/cpu/Decoder.scala:86:7, :132:22, :151:12, :158:14, :162:{26,46}, :164:27, :168:{45,49,59}, :170:{22,64}, :172:18, :177:25, :178:71, :180:18, :186:{48,71}, :187:18, :194:{18,24,27}, :210:{46,85,92}, :212:{15,21}, :214:18, :216:28, :218:18, :223:18, :232:{47,92}, :234:{22,37}, :235:{17,23}, :237:20, :243:20, :247:{29,48,80}, :248:18, :252:{29,78,110}, :254:16, :258:{28,47}, :260:16, :263:{29,47}, :265:{16,22}, :277:{28,47}, :279:{16,22}, :283:48, :289:19, :291:{22,41}, :292:{24,42}, :294:18, :296:37, :303:{17,23}, :313:26, :316:{29,48}, :318:16, :323:28, :324:{29,51}, :333:23, :335:20, :340:20, :350:20, :357:20, :363:{29,51}, :370:{20,29}, :371:18, :375:{27,36}, :376:18, :380:{27,36}, :381:18, :387:18, :390:{29,50}, :392:16, :399:{20,29,49}, :400:{15,28}, :402:{17,23}, :403:20, :405:20, :415:24, :416:{18,32}, :421:25, :424:{29,48}, :426:21, :441:{29,49}, :443:{16,22,25}, :449:{29,49}, :451:{16,22,25}, :457:49, :460:16, :471:52, :473:16, :478:{29,49}, :479:43, :481:18, :483:{30,50}, :485:18, :490:{48,79}, :492:21, :494:18, :499:18, :504:{29,49}, :514:{29,50}, :516:16, :519:{29,49}, :521:22, :523:18, :531:18
  assign io_decoded_condition =
    _GEN_0
      ? 4'hF
      : io_thumb
          ? (_GEN_18 | _GEN_20 | _GEN_22 | _GEN_28 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35
             | _GEN_36 | _GEN_41 | ~_GEN_39 | _GEN_40
               ? 4'hE
               : decodeReg[11:8])
          : decodeReg[31:28];	// src/main/scala/gba/cpu/Decoder.scala:86:7, :132:22, :151:12, :152:17, :162:{26,46}, :163:19, :164:27, :166:{19,24}, :289:19, :291:{22,41}, :316:{29,48}, :324:{29,51}, :363:{29,51}, :390:{29,50}, :399:{29,49}, :424:{29,48}, :441:{29,49}, :449:{29,49}, :457:49, :471:52, :478:{29,49}, :479:{15,43}, :481:18, :483:{30,50}, :485:18
  assign io_decoded_regN =
    io_thumb
      ? (_GEN_18
           ? {1'h0, _GEN_19 ? decodeReg[2:0] : decodeReg[5:3]}
           : _GEN_20
               ? _GEN_21
               : _GEN_22
                   ? {1'h0,
                      _GEN_23 | _GEN_24 | ~_GEN_25 ? decodeReg[2:0] : decodeReg[5:3]}
                   : _GEN_28
                       ? {decodeReg[7], decodeReg[2:0]}
                       : _GEN_32
                           ? 4'hF
                           : _GEN_33
                               ? {1'h0, decodeReg[9] ? decodeReg[5:3] : decodeReg[5:3]}
                               : _GEN_34
                                   ? {1'h0, decodeReg[5:3]}
                                   : _GEN_35
                                       ? {1'h0, decodeReg[5:3]}
                                       : _GEN_36
                                           ? 4'hD
                                           : _GEN_37
                                               ? {2'h3, ~(decodeReg[11]), 1'h1}
                                               : _GEN_38 | _GEN_42
                                                   ? 4'hD
                                                   : _GEN_43
                                                       ? {1'h0, decodeReg[10:8]}
                                                       : 4'hF)
      : _GEN_2
          ? (_GEN_4
               ? decodeReg[15:12]
               : _GEN_5 ? decodeReg[15:12] : _GEN_6 ? decodeReg[19:16] : decodeReg[19:16])
          : _GEN_10 ? decodeReg[19:16] : _GEN_16 ? decodeReg[19:16] : decodeReg[19:16];	// src/main/scala/gba/cpu/Decoder.scala:86:7, :115:27, :119:30, :132:22, :163:19, :164:27, :168:{49,59}, :170:{41,64}, :175:{18,23}, :178:{48,71}, :183:{18,23}, :186:{48,71}, :189:{18,23}, :199:{18,23}, :210:{46,92}, :223:18, :230:{16,21}, :232:92, :263:{29,47}, :272:{16,21}, :277:47, :280:21, :291:{22,41}, :292:{24,42}, :296:37, :299:23, :300:18, :311:{18,23}, :316:{29,48}, :320:16, :321:16, :324:{29,51}, :327:21, :328:16, :329:21, :333:23, :363:{29,51}, :368:{25,32}, :369:{16,22}, :390:{29,50}, :396:16, :399:{29,49}, :400:{15,28}, :402:{17,23}, :403:20, :405:20, :408:{18,23}, :417:{18,23}, :424:{29,48}, :438:{16,21}, :441:{29,49}, :446:{16,21}, :449:{29,49}, :455:16, :457:{29,49}, :463:21, :465:18, :468:18, :471:{28,52}, :476:16, :478:49, :490:{48,79}, :503:16, :504:{29,49}, :511:{16,21}, :514:50
  assign io_decoded_regD =
    io_thumb
      ? (_GEN_18
           ? {1'h0, _GEN_19 ? decodeReg[2:0] : decodeReg[2:0]}
           : _GEN_20
               ? _GEN_21
               : _GEN_22
                   ? {1'h0, decodeReg[2:0]}
                   : _GEN_28
                       ? {decodeReg[7], decodeReg[2:0]}
                       : _GEN_32
                           ? {1'h0, decodeReg[10:8]}
                           : _GEN_33
                               ? {1'h0, decodeReg[9] ? decodeReg[2:0] : decodeReg[2:0]}
                               : _GEN_34
                                   ? {1'h0, decodeReg[2:0]}
                                   : _GEN_35
                                       ? {1'h0, decodeReg[2:0]}
                                       : _GEN_36
                                           ? {1'h0, decodeReg[10:8]}
                                           : _GEN_37
                                               ? {1'h0, decodeReg[10:8]}
                                               : _GEN_38 ? 4'hD : 4'hE)
      : _GEN_2
          ? (_GEN_4
               ? decodeReg[19:16]
               : _GEN_5 ? decodeReg[19:16] : _GEN_6 ? decodeReg[15:12] : decodeReg[15:12])
          : _GEN_10 ? decodeReg[15:12] : _GEN_11 ? decodeReg[15:12] : decodeReg[15:12];	// src/main/scala/gba/cpu/Decoder.scala:86:7, :119:30, :132:22, :152:17, :164:27, :168:{49,59}, :170:{41,64}, :176:{18,23}, :178:{48,71}, :184:{18,23}, :186:{48,71}, :190:{18,23}, :200:{18,23}, :210:{46,92}, :231:{16,21}, :232:{47,92}, :234:37, :245:25, :252:110, :273:21, :291:{22,41}, :292:{24,42}, :296:37, :299:{18,23}, :312:{18,23}, :316:{29,48}, :320:16, :324:{29,51}, :327:{16,21}, :363:{29,51}, :368:{16,22,25,32}, :390:{29,50}, :397:{16,21}, :399:{29,49}, :400:{15,28}, :409:{18,23}, :418:{18,23}, :424:{29,48}, :439:{16,21}, :441:{29,49}, :447:{16,21}, :449:{29,49}, :454:{16,21}, :457:{29,49}, :459:{16,21}, :471:{28,52}, :475:16, :478:49
  assign io_decoded_regS =
    io_thumb
      ? (_GEN_22
           ? {1'h0,
              _GEN_23 | _GEN_24 | _GEN_25 | ~_GEN_27 ? decodeReg[5:3] : decodeReg[2:0]}
           : decodeReg[6:3])
      : _GEN_2 ? (_GEN_4 ? decodeReg[11:8] : decodeReg[11:8]) : decodeReg[11:8];	// src/main/scala/gba/cpu/Decoder.scala:86:7, :119:30, :132:22, :164:27, :168:{49,59}, :170:{41,64}, :174:{18,23}, :178:71, :182:23, :210:92, :224:23, :291:41, :324:{29,51}, :327:21, :329:21, :330:16, :333:23, :363:51, :366:21
  assign io_decoded_regM =
    io_thumb
      ? (_GEN_18
           ? {1'h0, _GEN_19 ? decodeReg[5:3] : decodeReg[8:6]}
           : _GEN_22
               ? {1'h0, _GEN_26 ? decodeReg[5:3] : decodeReg[2:0]}
               : _GEN_28
                   ? decodeReg[6:3]
                   : {1'h0, decodeReg[9] ? decodeReg[8:6] : decodeReg[8:6]})
      : _GEN_2
          ? (_GEN_4
               ? decodeReg[3:0]
               : _GEN_5 ? decodeReg[3:0] : _GEN_6 ? decodeReg[3:0] : decodeReg[3:0])
          : _GEN_10
              ? (decodeReg[4] ? decodeReg[3:0] : decodeReg[3:0])
              : _GEN_12 ? decodeReg[3:0] : decodeReg[3:0];	// src/main/scala/gba/cpu/Decoder.scala:86:7, :119:30, :132:22, :164:27, :168:{45,49,59}, :170:{41,64}, :173:{18,23}, :178:{48,71}, :181:{18,23}, :186:{48,71}, :191:{18,23}, :208:{18,23}, :210:{46,92}, :212:21, :216:28, :220:{18,23}, :226:{18,23}, :232:92, :234:{22,37}, :235:23, :240:25, :247:80, :250:23, :291:{22,41}, :292:{24,42}, :298:{18,23}, :310:{18,23}, :316:48, :324:{29,51}, :327:21, :329:{16,21}, :333:23, :337:25, :363:{29,51}, :366:{16,21}, :390:50, :400:{15,28}, :410:{18,23}, :419:{18,23}
  assign io_decoded_immediate =
    io_thumb
      ? (_GEN_18
           ? (_GEN_19
                ? {17'h0, decodeReg[10:6], decodeReg[12:11]}
                : decodeReg[10] ? {21'h0, decodeReg[8:6]} : 24'h0)
           : _GEN_20
               ? {16'h0, decodeReg[7:0]}
               : _GEN_22
                   ? (_GEN_26
                        ? 24'h0
                        : {22'h0,
                           _io_decoded_immediate_T_22
                             ? 2'h2
                             : _io_decoded_immediate_T_20
                                 ? 2'h1
                                 : _io_decoded_immediate_T_18 ? 2'h0 : 2'h3})
                   : _GEN_28
                       ? 24'h0
                       : _GEN_32
                           ? {14'h0, decodeReg[7:0], 2'h0}
                           : _GEN_33
                               ? 24'h0
                               : _GEN_34
                                   ? (decodeReg[12]
                                        ? {19'h0, decodeReg[10:6]}
                                        : {17'h0, decodeReg[10:6], 2'h0})
                                   : _GEN_35
                                       ? {18'h0, decodeReg[10:6], 1'h0}
                                       : _GEN_36
                                           ? {14'h0, decodeReg[7:0], 2'h0}
                                           : _GEN_37
                                               ? {16'hF, decodeReg[7:0]}
                                               : _GEN_38
                                                   ? {17'h1E, decodeReg[6:0]}
                                                   : _GEN_39
                                                       ? {13'h0,
                                                          {3{decodeReg[7]}},
                                                          decodeReg[7:0]}
                                                       : _GEN_42
                                                           ? (decodeReg[11]
                                                                ? {8'h0,
                                                                   decodeReg[8],
                                                                   7'h0,
                                                                   decodeReg[7:0]}
                                                                : {9'h0,
                                                                   decodeReg[8],
                                                                   6'h0,
                                                                   decodeReg[7:0]})
                                                           : _GEN_43
                                                               ? {16'h0, decodeReg[7:0]}
                                                               : {13'h0,
                                                                  _GEN_44
                                                                    ? decodeReg[10:0]
                                                                    : decodeReg[11]
                                                                        ? decodeReg[10:0]
                                                                        : decodeReg[10:0]})
      : _GEN_2
          ? (decodeReg[22] ? {16'h0, decodeReg[11:8], decodeReg[3:0]} : 24'h0)
          : _GEN_10
              ? (decodeReg[25]
                   ? {12'h0, decodeReg[11:0]}
                   : decodeReg[4] ? {22'h0, decodeReg[6:5]} : {17'h0, decodeReg[11:5]})
              : _GEN_14
                  ? {12'h0, decodeReg[11:0]}
                  : _GEN_15
                      ? decodeReg[23:0]
                      : _GEN_16
                          ? {12'h0,
                             decodeReg[25] ? {5'h0, decodeReg[11:5]} : decodeReg[11:0]}
                          : {8'h0, decodeReg[15:0]};	// src/main/scala/gba/cpu/Decoder.scala:86:7, :111:25, :119:30, :132:22, :158:52, :164:27, :168:{45,49,59}, :170:{55,64}, :177:25, :198:45, :201:23, :203:{25,34,45}, :206:25, :210:{46,92}, :212:{15,21}, :215:{23,28}, :216:28, :219:{23,28}, :223:18, :225:{23,28}, :232:92, :247:62, :252:{78,110}, :257:{21,26}, :258:{28,47}, :262:{21,26}, :263:{29,47}, :271:47, :274:{21,27,38,49}, :277:47, :282:{21,26}, :291:{22,41}, :292:{15,24,42}, :295:{23,32}, :303:{17,23}, :305:{25,30}, :308:25, :316:{29,48}, :322:{21,26}, :324:{29,51}, :333:23, :337:25, :342:{25,68}, :363:{29,51}, :370:29, :390:{29,50}, :398:{21,30}, :399:{29,49}, :400:28, :402:17, :424:{29,48}, :431:{15,21}, :433:{23,28}, :436:{23,28}, :441:{29,49}, :445:{21,26}, :449:{29,49}, :453:{21,26}, :457:{29,49}, :462:{21,46}, :471:{28,52}, :477:{21,47}, :478:{29,49}, :479:43, :488:{23,34,40,48}, :490:{48,79}, :492:21, :495:{23,29,32,49}, :500:{23,29,42,59}, :504:{29,49}, :512:{21,26}, :514:{29,50}, :518:{21,26}, :519:49, :521:22, :527:{23,28}, :532:{23,28}
  assign io_decoded_opcode =
    _GEN_0
      ? 4'h2
      : io_thumb
          ? (_GEN_18
               ? (_GEN_19 ? 4'hD : {1'h0, decodeReg[9] ? 3'h2 : 3'h4})
               : _GEN_20
                   ? _io_decoded_opcode_WIRE[decodeReg[12:11]]
                   : _GEN_22
                       ? (_GEN_23 ? decodeReg[9:6] : _GEN_24 ? 4'hD : {3'h1, _GEN_25})
                       : _GEN_28
                           ? _GEN[decodeReg[9:8]]
                           : _GEN_32
                               ? 4'h2
                               : _GEN_33
                                   ? (decodeReg[9]
                                        ? {3'h0, decodeReg[11:10] != 2'h1}
                                        : {2'h0, ~(decodeReg[10]), 1'h0})
                                   : _GEN_34
                                       ? {2'h0, ~(decodeReg[12]), 1'h0}
                                       : _GEN_35
                                           ? 4'h1
                                           : _GEN_36
                                               ? 4'h2
                                               : _GEN_37
                                                   ? 4'h4
                                                   : _GEN_38
                                                       ? {1'h0,
                                                          decodeReg[7] ? 3'h2 : 3'h4}
                                                       : _GEN_39
                                                           ? {3'h1, &(decodeReg[11:8])}
                                                           : _GEN_42 | _GEN_43 | _GEN_44
                                                             | ~_GEN_45
                                                               ? 4'h2
                                                               : 4'h4)
          : _GEN_2
              ? (_GEN_7
                   ? 4'h2
                   : _GEN_6 ? {2'h0, ~(decodeReg[22]), 1'h0} : {3'h0, decodeReg[5]})
              : _GEN_10
                  ? decodeReg[24:21]
                  : _GEN_11
                      ? (_GEN_12 & decodeReg[21] ? decodeReg[19:16] : 4'h2)
                      : _GEN_14
                          ? decodeReg[19:16]
                          : _GEN_15
                              ? 4'h2
                              : _GEN_16
                                  ? {2'h0, ~(decodeReg[22]), 1'h0}
                                  : _GEN_17 ? 4'h2 : {3'h1, &(decodeReg[27:24])};	// src/main/scala/gba/cpu/Decoder.scala:86:7, :119:30, :132:22, :158:14, :159:13, :162:{26,46}, :164:27, :168:{22,49,59}, :170:64, :172:18, :177:25, :178:71, :180:18, :186:{48,71}, :188:{20,26,29}, :194:24, :195:{20,29}, :210:{46,92}, :228:{18,23}, :232:{47,92}, :234:{22,37}, :235:{17,23}, :239:{22,27}, :247:{29,62}, :252:{29,78,110}, :256:{18,23}, :258:{28,47}, :263:{29,47}, :266:{18,24,27}, :277:{28,47}, :283:{19,28,48}, :285:18, :291:{22,41}, :292:{24,42}, :296:{20,37}, :313:{20,26,29}, :316:{29,48}, :323:{18,28,96,106}, :324:{29,51}, :332:22, :333:23, :336:22, :341:22, :351:22, :363:{29,51}, :365:22, :370:{20,29}, :372:20, :375:{27,36}, :377:20, :380:{27,36}, :382:20, :390:{29,50}, :393:18, :399:{29,49}, :400:{15,28}, :407:{20,26,29}, :415:24, :422:{20,34}, :424:{29,48}, :431:{15,21}, :432:20, :435:20, :441:{29,49}, :444:18, :449:{29,49}, :452:18, :457:{29,49}, :461:18, :471:{28,52}, :474:{18,24,27}, :478:{29,49}, :479:{15,23,43}, :482:20, :490:{48,79}, :504:{29,49}, :514:{29,50}, :519:49, :521:22, :526:19
  assign io_decoded_flags =
    _GEN_0
      ? 7'h0
      : io_thumb
          ? (_GEN_18 | _GEN_20 | _GEN_22
               ? 7'h1
               : _GEN_28
                   ? (_GEN_29 ? 7'h0 : _GEN_30 ? 7'h1 : {5'h0, ~_GEN_31, 1'h0})
                   : _GEN_32
                       ? 7'h4E
                       : _GEN_33
                           ? (decodeReg[9] ? {2'h0, decodeReg[10], 4'h6} : 7'h6)
                           : _GEN_34 | _GEN_35 | _GEN_36
                               ? 7'hE
                               : _GEN_37
                                   ? {4'h0, ~(decodeReg[11]), 2'h0}
                                   : _GEN_38
                                       ? 7'h0
                                       : _GEN_39
                                           ? {4'h0, ~_GEN_40, 2'h0}
                                           : _GEN_42
                                               ? (decodeReg[11] ? 7'h5 : 7'h9)
                                               : _GEN_43
                                                   ? 7'h5
                                                   : _GEN_44
                                                       ? 7'h4
                                                       : {5'h0, _GEN_45, 1'h0})
          : _GEN_2
              ? (_GEN_4
                   ? {5'h0, decodeReg[21:20]}
                   : _GEN_5
                       ? {4'h1, decodeReg[22:20]}
                       : _GEN_6
                           ? 7'h0
                           : {2'h0,
                              decodeReg[6],
                              decodeReg[22],
                              decodeReg[24:23],
                              ~(decodeReg[24]) | decodeReg[21]})
              : _GEN_10
                  ? {6'h0, decodeReg[20]}
                  : _GEN_11
                      ? (_GEN_12
                           ? {6'h0, decodeReg[21] ? decodeReg[22] : decodeReg[22]}
                           : {5'h0, _GEN_13, 1'h0})
                      : _GEN_14
                          ? {6'h1, decodeReg[22]}
                          : _GEN_15
                              ? {6'h0, decodeReg[24]}
                              : _GEN_16
                                  ? {1'h0,
                                     ~(decodeReg[24]) & decodeReg[21],
                                     1'h0,
                                     ~(decodeReg[25]),
                                     decodeReg[24:23],
                                     ~(decodeReg[24]) | decodeReg[21]}
                                  : _GEN_17 ? {3'h0, decodeReg[24:21]} : 7'h0;	// src/main/scala/gba/cpu/Decoder.scala:86:7, :119:30, :132:22, :151:12, :159:13, :162:{26,46}, :164:27, :168:{22,49,59}, :170:{41,55,64}, :177:{19,25,38}, :178:{48,71}, :185:{19,38}, :186:{48,71}, :196:{25,28,33,38}, :198:{19,25,38,45}, :210:{46,85,92}, :229:17, :232:{47,92}, :234:{22,37}, :235:{17,23}, :238:{21,43}, :244:{21,26}, :247:{29,48,80}, :249:19, :252:{78,110}, :255:{17,39}, :258:{28,47}, :261:{17,39}, :263:{29,47}, :269:{22,25,30,35}, :270:{23,31}, :271:{17,23,44,47}, :277:{28,47}, :281:{17,22}, :291:{22,41}, :292:42, :297:19, :316:{29,48}, :319:17, :324:{29,51}, :333:23, :363:{29,51}, :370:{20,29}, :373:19, :375:{27,36}, :378:19, :380:{27,36}, :383:19, :388:19, :390:{29,50}, :395:17, :399:{29,49}, :400:{15,28}, :402:{17,23}, :403:20, :405:20, :412:19, :421:{19,25,28}, :424:{29,48}, :440:17, :441:{29,49}, :448:17, :449:{29,49}, :456:17, :457:{29,49}, :463:21, :469:19, :471:{28,52}, :478:{29,49}, :479:43, :481:18, :483:{30,50}, :485:18, :487:19, :490:{48,79}, :492:21, :495:29, :496:19, :500:29, :501:19, :504:{29,49}, :513:17, :514:{29,50}, :517:17, :519:49, :521:22, :526:19
endmodule

