// Generated by CIRCT firtool-1.62.0
module Multiplier(	// src/main/scala/gba/cpu/Multiplier.scala:6:7
  input         clock,	// src/main/scala/gba/cpu/Multiplier.scala:6:7
                io_enable,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
  input  [31:0] io_a,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_b,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
  input         io_start,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_loadAccumulator,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_accumulate,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_signed,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_long,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
  output [31:0] io_outLo,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_outHi,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
  output        io_done,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_outFlagZ,	// src/main/scala/gba/cpu/Multiplier.scala:7:14
                io_outFlagN	// src/main/scala/gba/cpu/Multiplier.scala:7:14
);

  reg [63:0] accumulator;	// src/main/scala/gba/cpu/Multiplier.scala:26:24
  reg [63:0] output_0;	// src/main/scala/gba/cpu/Multiplier.scala:27:19
  reg [1:0]  counter;	// src/main/scala/gba/cpu/Multiplier.scala:28:20
  always @(posedge clock) begin	// src/main/scala/gba/cpu/Multiplier.scala:6:7
    if (io_enable & io_loadAccumulator)	// src/main/scala/gba/cpu/Multiplier.scala:26:24, :42:20, :43:31, :44:19
      accumulator <= {io_a, io_b};	// src/main/scala/gba/cpu/Multiplier.scala:26:24, :44:25
    if (io_enable & io_start) begin	// src/main/scala/gba/cpu/Multiplier.scala:27:19, :42:20, :46:21, :50:24
      automatic logic [63:0] augend = io_accumulate ? accumulator : 64'h0;	// src/main/scala/gba/cpu/Multiplier.scala:26:24, :47:23
      output_0 <=
        io_signed
          ? {{32{io_a[31]}}, io_a} * {{32{io_b[31]}}, io_b} + augend
          : {32'h0, io_a} * {32'h0, io_b} + augend;	// src/main/scala/gba/cpu/Multiplier.scala:27:19, :47:23, :50:24, :51:{16,32,54}, :53:{16,25,33}
    end
    if (io_enable) begin	// src/main/scala/gba/cpu/Multiplier.scala:7:14
      if (|counter)	// src/main/scala/gba/cpu/Multiplier.scala:28:20, :57:19
        counter <= counter - 2'h1;	// src/main/scala/gba/cpu/Multiplier.scala:28:20, :58:26
      else if (io_start) begin	// src/main/scala/gba/cpu/Multiplier.scala:7:14
        automatic logic _prefixZeroes_T_2 = io_b[31:24] == 8'h0;	// src/main/scala/gba/cpu/Multiplier.scala:33:{35,44}
        automatic logic _prefixZeroes_T_5 = io_b[23:16] == 8'h0;	// src/main/scala/gba/cpu/Multiplier.scala:33:{44,54,63}
        automatic logic _termOnes_T_1 = io_long & ~io_signed;	// src/main/scala/gba/cpu/Multiplier.scala:35:{28,31}
        counter <=
          (&{io_b[15:8] == 8'h0, _prefixZeroes_T_5, _prefixZeroes_T_2})
          | (&{&(io_b[15:8]), &(io_b[23:16]), &(io_b[31:24])}) & ~_termOnes_T_1
            ? 2'h0
            : (&{_prefixZeroes_T_5, _prefixZeroes_T_2})
              | (&{&(io_b[23:16]), &(io_b[31:24])}) & ~_termOnes_T_1
                ? 2'h1
                : {1'h1, ~(_prefixZeroes_T_2 | (&(io_b[31:24])) & ~_termOnes_T_1)};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/gba/cpu/Multiplier.scala:28:20, :33:{35,44,54,63,73,81}, :34:{41,60,78}, :35:{18,28}, :37:{18,25,38,52,59,72}, :38:{18,25,37,51,58,70}, :39:{25,36,68}
      end
    end
  end // always @(posedge)
  assign io_outLo = output_0[31:0];	// src/main/scala/gba/cpu/Multiplier.scala:6:7, :27:19, :62:22
  assign io_outHi = output_0[63:32];	// src/main/scala/gba/cpu/Multiplier.scala:6:7, :27:19, :63:22
  assign io_done = counter == 2'h0;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/gba/cpu/Multiplier.scala:6:7, :28:20, :65:22
  assign io_outFlagZ = (~io_long | output_0[63:32] == 32'h0) & output_0[31:0] == 32'h0;	// src/main/scala/gba/cpu/Multiplier.scala:6:7, :27:19, :53:25, :62:{22,30}, :63:{22,31}, :68:21
  assign io_outFlagN = io_long ? output_0[63] : output_0[31];	// src/main/scala/gba/cpu/Multiplier.scala:6:7, :27:19, :69:{21,37,49}
endmodule

