// Generated by CIRCT firtool-1.62.0
module Shifter(	// src/main/scala/gba/cpu/Shifter.scala:14:7
  input         clock,	// src/main/scala/gba/cpu/Shifter.scala:14:7
  input  [31:0] io_in,	// src/main/scala/gba/cpu/Shifter.scala:15:14
  input  [2:0]  io_shiftKind,	// src/main/scala/gba/cpu/Shifter.scala:15:14
  input  [5:0]  io_shiftAmount,	// src/main/scala/gba/cpu/Shifter.scala:15:14
  output [31:0] io_out,	// src/main/scala/gba/cpu/Shifter.scala:15:14
  input         io_carryIn,	// src/main/scala/gba/cpu/Shifter.scala:15:14
  output        io_carryOut,	// src/main/scala/gba/cpu/Shifter.scala:15:14
  input         io_latchShift,	// src/main/scala/gba/cpu/Shifter.scala:15:14
                io_useLatchedShift	// src/main/scala/gba/cpu/Shifter.scala:15:14
);

  reg  [7:0]   latchedShift;	// src/main/scala/gba/cpu/Shifter.scala:33:25
  wire [7:0]   shiftAmount = io_useLatchedShift ? latchedShift : {2'h0, io_shiftAmount};	// src/main/scala/gba/cpu/Shifter.scala:33:25, :38:24
  wire         _GEN = io_shiftKind == 3'h0;	// src/main/scala/gba/cpu/Shifter.scala:42:25
  wire         _GEN_0 = shiftAmount == 8'h0;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :44:25
  wire         _GEN_1 = shiftAmount < 8'h20;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :47:32
  wire [286:0] _io_out_T = {255'h0, io_in} << shiftAmount;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :48:27
  wire [31:0]  _io_carryOut_T_3 = io_in >> 5'h0 - shiftAmount[4:0];	// src/main/scala/gba/cpu/Shifter.scala:38:24, :49:{31,38}, :96:27
  wire         _GEN_2 = shiftAmount == 8'h20;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :47:32, :50:32
  wire         _GEN_3 = io_shiftKind == 3'h1;	// src/main/scala/gba/cpu/Shifter.scala:42:25
  wire [31:0]  _GEN_4 = {24'h0, shiftAmount};	// src/main/scala/gba/cpu/Shifter.scala:38:24, :66:27
  wire [31:0]  _io_carryOut_T_10 = io_in >> shiftAmount[4:0] - 5'h1;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :49:38, :67:{31,45}
  wire         _GEN_5 = io_shiftKind == 3'h2;	// src/main/scala/gba/cpu/Shifter.scala:42:25
  wire [31:0]  _io_carryOut_T_16 = io_in >> shiftAmount[4:0] - 5'h1;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :49:38, :88:{31,45}
  wire         _GEN_6 = io_shiftKind == 3'h3;	// src/main/scala/gba/cpu/Shifter.scala:42:25
  wire         _GEN_7 = shiftAmount[4:0] == 5'h0;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :92:31, :96:27
  wire [31:0]  _io_out_T_13 = shiftAmount[0] ? {io_in[0], io_in[31:1]} : io_in;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :92:31, :100:38
  wire [31:0]  _io_out_T_17 =
    shiftAmount[1] ? {_io_out_T_13[1:0], _io_out_T_13[31:2]} : _io_out_T_13;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :92:31, :100:38
  wire [31:0]  _io_out_T_21 =
    shiftAmount[2] ? {_io_out_T_17[3:0], _io_out_T_17[31:4]} : _io_out_T_17;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :92:31, :100:38
  wire [31:0]  _io_out_T_25 =
    shiftAmount[3] ? {_io_out_T_21[7:0], _io_out_T_21[31:8]} : _io_out_T_21;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :92:31, :100:38
  wire [31:0]  _io_carryOut_T_21 = io_in >> shiftAmount[4:0] - 5'h1;	// src/main/scala/gba/cpu/Shifter.scala:38:24, :92:31, :101:{31,39}
  always @(posedge clock) begin	// src/main/scala/gba/cpu/Shifter.scala:14:7
    if (io_latchShift)	// src/main/scala/gba/cpu/Shifter.scala:15:14
      latchedShift <= io_in[7:0];	// src/main/scala/gba/cpu/Shifter.scala:33:25, :35:18
  end // always @(posedge)
  assign io_out =
    _GEN
      ? (_GEN_0 ? io_in : _GEN_1 ? _io_out_T[31:0] : 32'h0)
      : _GEN_3
          ? (_GEN_2 ? 32'h0 : _GEN_0 ? io_in : _GEN_1 ? io_in >> _GEN_4 : 32'h0)
          : _GEN_5
              ? ((|(shiftAmount[7:5]))
                   ? {32{io_in[31]}}
                   : _GEN_0 ? io_in : $signed($signed(io_in) >>> _GEN_4))
              : _GEN_6
                  ? (_GEN_0 | _GEN_7
                       ? io_in
                       : shiftAmount[4]
                           ? {_io_out_T_25[15:0], _io_out_T_25[31:16]}
                           : _io_out_T_25)
                  : {io_carryIn, io_in[31:1]};	// src/main/scala/gba/cpu/Shifter.scala:14:7, :38:24, :42:25, :44:{25,34}, :45:16, :47:{32,40}, :48:{16,27}, :50:{32,42}, :51:16, :59:35, :60:16, :62:41, :63:16, :65:40, :66:{16,27}, :69:16, :75:{25,34}, :76:{22,36}, :77:18, :79:18, :82:41, :83:16, :87:{16,35}, :92:31, :93:34, :94:16, :96:{27,36}, :97:16, :100:{16,38}, :106:{20,41}
  assign io_carryOut =
    _GEN
      ? (_GEN_0 ? io_carryIn : _GEN_1 ? _io_carryOut_T_3[0] : _GEN_2 & io_in[0])
      : _GEN_3
          ? (_GEN_2 ? io_in[31] : _GEN_0 ? io_carryIn : _GEN_1 & _io_carryOut_T_10[0])
          : _GEN_5
              ? ((|(shiftAmount[7:5]))
                   ? io_in[31]
                   : _GEN_0 ? io_carryIn : _io_carryOut_T_16[0])
              : _GEN_6
                  ? (_GEN_0 ? io_carryIn : _GEN_7 ? io_in[31] : _io_carryOut_T_21[0])
                  : io_in[0];	// src/main/scala/gba/cpu/Shifter.scala:14:7, :38:24, :42:25, :44:{25,34}, :46:21, :47:{32,40}, :49:{21,31}, :50:{32,42}, :52:{21,31}, :55:21, :59:35, :61:{21,31}, :62:41, :64:21, :65:40, :67:{21,31}, :70:21, :75:{25,34}, :76:22, :81:21, :82:41, :84:21, :88:{21,31}, :93:34, :95:21, :96:{27,36}, :98:{21,31}, :101:{21,31}, :107:29
endmodule

